lib/src/dart.dart

Pub crash in checked mode because spawnUri requires packageRoot to be a Uri, while here it can also be a String.

Fix for pub crashing in checked mode

---

lib/src/utils.dart
test/utils_test.dart

niceDuration used to display 61 second as "1:1" instead of "1:01". This patch fixes that and minute duration (which is 60 seconds last time I've checked) and adds couple of unit tests.

Change duration formatting in niceDuration

---

lib/src/io.dart

Where /var/ is really /private/var/
Eliminates two failures in test/run/package_api_test.dart

eliminate test failure on mac

---

lib/src/barback/asset_environment.dart
lib/src/dart.dart
lib/src/entrypoint.dart

Previously we were always loading an AssetEnvironment when we
precompiled any executable. Now we only load that environment if some
package dependended on by some executable actually uses a transformer.
Otherwise, we precompile from disk. The new approach is substantially
faster and produces better error messages.
Closes #1473

Avoid barback for precompilation if possible.

---

lib/src/io.dart

Add two flags to `tar` invocation that will provide consistent behavior whether `pub` is executed as root or a normal user.

Suggested patch for #1486

---

lib/src/executable.dart
test/run/app_can_read_from_stdin_test.dart

Properly close stdin for child processes.

---

lib/src/io.dart

3fa5df4d55328628d8c91560f61cfb1f92a003b7 added new flags between the
"--directory" flag and the directory in question, which broke untarring.

Fix extractTarGz().

---

lib/src/io.dart

This also changes tar creation on Linux to use "pub" as the user/group
rather than the ID 0, so people don't accidentally end up manually
extracting files with root ownership.
Closes #1442

Avoid invalid UIDs and GIDs on OS X.

---

lib/src/io.dart

That hits OS X too, and the version of tar on OS X doesn't support
those. :(

Disable passing "--uname" and "--gname" to tar on non-Linux.

---

test/serve/utils.dart

That occur due to type inference yelling a bit. No breaking changes.

Fix two strong-mode warnings

---

lib/src/utils.dart
lib/src/validator/strict_dependencies.dart
test/descriptor.dart
test/test_pub.dart
test/validator/strict_dependencies_test.dart

First step of https://github.com/dart-lang/pub/issues/343.
Implemented `StrictDependenciesValidator`, which crawls all source files, finds all referenced `import` and `export` directives, and compares them against all declared `dependencies` and `dev_dependencies`.
IMO this should be an error, not a warning, but wanted input first to see if I've possibly missed legitimate use cases where people should be able to override and upload anyway. Should this also be added as a flag to `pub` to opt-in or just added by default? I didn't do anything but implement the validator yet.
~~Future work:~~
~~- [ ] Validate you haven't declared dependencies you don't use (?)~~

First pass at strict dependencies

---

lib/src/io.dart

Fixes #1442 'UID too large' on Mac

Fixes #1442 'UID too large' on Mac

---

lib/src/io.dart
test/descriptor/tar.dart

Tracking down these two tiny changes was surprisingly hard.

Get the Mac tests passing again with the mtree stuff in tar.

---

test/descriptor.dart
test/descriptor/git.dart

Fixes #1535
The tests execute `git` in a number of places which is impacted by the
users global git config and can cause failure.
- Remove `info` and `hooks` from the list of required directories under
`.git`. These are controlled by the `init.templatedir` config and are
only the defaults but may not exist.
- For git repos created during the test configure `core.excludesfile` as
empty since we rely on having full control over ignored files when we
create `.gitignore` ourself.

Shield against global gitconfig in tests

---

.gitignore

The current ignore is too broach and matches some of the tests. A
leading slash makes the ignore only match a build directory at the root
of the repo

Don't ignore test/build/ directory

---

lib/src/command/build.dart
test/build/reports_failures_test.dart

Fixes #1336
Record when we log and error and mark the entire build as failed. This
catches the cases where there are errors on assets that did not
transitively impact dart2js output - like transformers on non-Dart
files.

Exit as failure if any transformer had an error

---

lib/src/validator/dependency.dart
test/validator/dependency_test.dart

Allow publishing packages with SDK dependencies on Flutter.

---

lib/src/barback/dartdevc/module.dart
lib/src/barback/dartdevc/module_reader.dart
test/barback/dartdevc/module_reader_test.dart
test/barback/dartdevc/module_test.dart
test/barback/dartdevc/util.dart

These provide the building blocks for storing information about modules that are created by a package.
The idea is that each top level folder under a package will have a single `.moduleConfig` file that describes all the modules under that folder. Modules will not be allowed to cross over top level folders or packages.

add Module/ModuleId/ModuleReader classes

---

lib/src/barback/dartdevc/dartdevc.dart
lib/src/barback/dartdevc/dartdevc_bootstrap_transformer.dart
lib/src/barback/dartdevc/dartdevc_module_transformer.dart
lib/src/barback/dartdevc/dartdevc_resource_transformer.dart
lib/src/barback/dartdevc/linked_summary_transformer.dart
lib/src/barback/dartdevc/module.dart
lib/src/barback/dartdevc/summaries.dart
lib/src/barback/dartdevc/unlinked_summary_transformer.dart
test/barback/dartdevc/linked_summary_transformer_test.dart
test/barback/dartdevc/module_config_transformer_test.dart
test/barback/dartdevc/unlinked_summary_transformer_test.dart

For the most part this is just moving code around, with some minor cleanup.
The apis no longer take a `Transform` for any of these methods so they are more general, and they all return either a `Map<AssetId, Future<Asset>>` or `Map<AssetId, Asset>` synchronously.

Move shared code into shared libraries, clean up args.

---

lib/src/command/build.dart
lib/src/dartdevc/dartdevc.dart
lib/src/dartdevc/dartdevc_environment.dart
lib/src/dartdevc/errors.dart
lib/src/dartdevc/module_reader.dart
lib/src/dartdevc/summaries.dart
lib/src/log.dart
test/compiler/reports_dart_parse_errors_test.dart

Added some new Exception types which are thrown instead of AssetNotFoundExceptions, and added uniform handling for them which creates a new asset at `originalId.addExtension('.errors')`.
This new asset is requested by the app when it fails to load a module and it prints the contents to the console so you can get compilation errors in your browser.
Partially resolves https://github.com/dart-lang/pub/issues/1618, I think we could still do something better with these errors but this is a good first step.

Improve/unify error handling, plumb through compilation errors to the browser console

---

lib/src/cached_package.dart
lib/src/command/barback.dart
lib/src/pubspec.dart
test/compiler/compiler_selection_test.dart
test/compiler/compiles_entrypoints_in_root_package_test.dart
test/compiler/environment_constant_test.dart
test/compiler/ignores_entrypoints_in_lib_test.dart
test/compiler/ignores_non_entrypoint_dart_files_test.dart
test/compiler/includes_source_maps_in_debug_test.dart
test/compiler/omits_source_map_in_release_test.dart
test/compiler/reports_dart_parse_errors_test.dart
test/compiler/source_maps_are_self_contained_test.dart
test/compiler/supports_configuration_with_build_test.dart
test/compiler/utils.dart
test/dartdevc/build_test.dart
test/dartdevc/dartdevc_test.dart
test/dartdevc/module_config_test.dart
test/dartdevc/summaries_test.dart
test/pubspec_test.dart
test/serve/utils.dart

With the top level key in the pubspec being called `js-compiler`, it no longer makes sense for the command line arg to be just `compiler` (same argument holds about future compilers conflicting). Since `js-compiler` is really long I talked with @munificent and we landed on just `--js`.
Let me know if there are objections to changing the flag from `--compiler` to `--js`. If we could come up with a single character shorthand for `--js-compiler` that might be preferable, but I don't know of one that really makes sense.
cc @kevmoo @munificent @jwren @devoncarew 
EDIT: See comment below about naming changes

add web compiler option to pubspec.yaml, change --compiler to --web-compiler

---

lib/src/http.dart

...instead of info.
Allows capturing response information in the case of 5xx errors without
requiring verbose logging
Related to https://github.com/dart-lang/pub-dartlang-dart/issues/94

Log HTTP requests/responses to the IO log

---

lib/src/dartdevc/dartdevc.dart

`e.originalError` doesn't always exist (for timeout errors for instance), now we will only try to fetch the `.errors` file (and log the errors to the console) if `e.originalError.srcElement` exists.

only fetch .errors file for script load errors

---

pubspec.yaml

We were already passing allowTrailingOptions to all ArgParser
call-sites, so this doesn't require any code changes.

Support args 1.0.0.

---

lib/src/dartdevc/dartdevc.dart

Fixes https://github.com/dart-lang/pub/issues/1644
We could make this configurable but I don't think there is much value in that.

remove the require.js timeout for module loading

---

lib/src/pubspec.dart
lib/src/solver/backtracking_solver.dart
test/pubspec_test.dart
test/version_solver_test.dart

Enabling multiple dependencies is necessary for some use-cases for
issue #1593 like having a package expose a feature that enables a
feature in a dependency, or having a package expose a "testing"
feature and also depend on test from its dev dependencies.
For consistency with features, this also removes the restriction that
a pubspec may not have a normal and dev dependency on the same
package.

Allow multiple dependencies from one package onto another

---

lib/src/pubspec.dart
test/pubspec_test.dart
test/validator/dependency_test.dart
test/validator/sdk_constraint_test.dart
test/version_solver_test.dart

Packages that don't declare an SDK constraint will now be considered
compatible with SDK versions matching <2.0.0-dev.infinity.
Closes #1657

Add a default SDK constraint

---

lib/src/command/lish.dart

Fixes https://github.com/dart-lang/pub-dartlang-dart/issues/230

Set the content type during publish to application/gzip

---

lib/src/command/lish.dart

This reverts commit 3e4890f1e45e94ae7bad416cda7b5632bf67275a.
Does not fix https://github.com/dart-lang/pub/issues/1666
Tracking internally here http://b/63855519

Revert "Set the content type during publish to application/gzip (#1671)"

---

lib/src/command/run.dart
test/run/errors_if_no_executable_is_given_test.dart
test/run/errors_if_path_in_dependency_test.dart
test/run/list_test.dart

Add "pub run --list" command to show all available executables.

---

test/dartdevc/summaries_test.dart

As of https://github.com/dart-lang/sdk/commit/5b29ae48adcadc6f5f98c6ee937d4bb7c8414c83 the analyzer_cli no longer records summary deps, so the summary test started failing.
Fixes https://github.com/dart-lang/pub/issues/1687.

Update the summary test to not expect summary deps which arent recorded any more

---

lib/src/dartdevc/dartdevc.dart

Fixes https://github.com/dart-lang/sdk/issues/30246
Note that there is no sane way I know of to actually write an e2e test for this because package:test requires the html file to have the same name as the dart file but with the .html extension.... :(

Allow including script tags pointing to subdirs with dartdevc

---

lib/src/cached_package.dart
lib/src/entrypoint.dart
lib/src/pubspec.dart
lib/src/validator.dart
lib/src/validator/sdk_constraint.dart
test/pubspec_test.dart
test/upgrade/report/describes_change_test.dart
test/upgrade/report/does_not_show_newer_versions_for_locked_packages_test.dart
test/upgrade/report/leading_character_shows_change_test.dart
test/upgrade/report/shows_newer_available_versions_test.dart
test/version_solver_test.dart

Also introduces the PUB_ALLOW_PRERELEASE_SDK environment variable which can override this behavior. Valid values are `true` (default), `false`, and `quiet` (true but no log message about the override).
Fixes https://github.com/dart-lang/pub/issues/1692

Add default upper bound Dart SDK constraint override from 2.0.0 -> 2.0.0-dev.infinity

---

lib/src/command/lish.dart
lib/src/http.dart

Fixes https://github.com/dart-lang/pub/issues/1706
Validated manually that this works, but I don't think its worth figuring out how to write a real test. In the test runner its not hooked into a console so the log colors don't do anything.
cc @kevmoo

log red on server errors when publishing, or green on success

---

lib/src/pubspec.dart

Looks like the features env variable revert removed a dart:io import which was relied upon by a susequent change.

add back dart:io import to pubspec.dart

---

lib/src/command_runner.dart
lib/src/source/hosted.dart

Emit exit code 69 for TlsExceptions

---

lib/src/compiler.dart

We were passing an Iterable in place of a List, but an implicit cast
was hiding it from analysis and it worked in practice in unchecked
mode.

Fix a bug that only showed up in checked mode

---

lib/src/barback/dependency_computer.dart
lib/src/cached_package.dart
lib/src/command/build.dart
lib/src/command/deps.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/package.dart
lib/src/package_graph.dart
lib/src/pubspec.dart
lib/src/solver/backtracking_solver.dart
lib/src/solver/unselected_package_queue.dart
lib/src/solver/version_solver.dart
lib/src/validator/dependency.dart
lib/src/validator/dependency_override.dart
lib/src/validator/strict_dependencies.dart
test/dependency_computer/utils.dart
test/pubspec_test.dart
test/version_solver_test.dart

This cleans up some existing code, but more importantly it makes some
algorithms for the new version solver more efficient.

Represent Pubspec.dependencies as a map

---

lib/src/validator/dependency.dart
test/validator/dependency_test.dart

This will allow users to play with package features locally without
putting them into the package ecosystem.

Don't allow package features to be published (yet)

---

lib/src/barback/transformer_isolate.dart
lib/src/pubspec.dart
lib/src/utils.dart
test/descriptor_server.dart

https://github.com/dart-lang/sdk/issues/31384 was fixed in
https://github.com/dart-lang/sdk/commit/0a6253312f
Available in Dart 2.0.0-dev.12.0

Annotate fail with @alwaysThrows, Remove unreachable throws

---

lib/src/http.dart

Closes https://github.com/dart-lang/pub/issues/1556

Fix retry logic

---

lib/src/pubspec.dart
test/version_solver_test.dart

Previously, if the user was using 1.2.3-dev.1 and a package had an SDK
constraint ">=1.2.3-dev.2", we would try to create an invalid
">=1.2.3-dev.2 <1.2.3-dev.1" constraint.
Closes #1770

Don't adjust SDK constraints whose min versions are prerelease

---

lib/src/pubspec.dart
test/version_solver_test.dart

We'd previously been disabling SDK overrides any time the minimum
constraint was a pre-release version, whether or not that version had
anything to do with the SDK. We not only disable the overrides when
the minimum constraint is a pre-release version *of the current SDK*.
Closes #1781
Closes #1780
See dart-lang/sdk#31926
See dart-lang/sdk#31940

Fix another bug in SDK override logic

---

doc/solver.md
lib/src/package_name.dart
lib/src/solver/package_lister.dart
lib/src/solver/version_solver.dart

We now use the same logic to select a version and add
incompatibilities for the root package that we do for every other
package. This makes it easier to write logic that treats the root
package the same way as other packages.

Use less special-casing for the root package

---

lib/src/barback/dart2js_transformer.dart
lib/src/barback/pub_package_provider.dart
lib/src/dart.dart

Dart2js needs an extra argument to locate the dart2js_platform.dill file. The provider for the compiler needs to read this file as a binary file.
This change is necessary before we can make dart2js use the CFE by default.
Two questions:
* do you need `compiler_unsupported` to get updated? Its current version doesn't have the `--platform-binaries` flag. I'm investigating what's the process to update that package, but it appears we are not running dart2js as part of pub tests (when I run `pub run test`, all tests pass.)
* do we need to indicate a minimal sdk version where this pub will work? (I assume that it might not be needed, because pub is always shipped with the sdk.

Allow dart2js to compile with the CFE.

---

lib/src/barback/dart2js_transformer.dart
lib/src/dart.dart

Note: the `.packages` file is not available as an asset, so it wont be emitted in the output build folder. If you want to make it a asset, could you please give me some hints as to where/how I should do so?

Reenable the common front-end in dart2js by creating a .packages file

---

lib/src/http.dart
pubspec.yaml

Retry HTTP requests when they fail due to IO errors

---

lib/src/command/barback.dart
lib/src/log.dart
test/barback/utils.dart
test/compiler/does_not_support_invalid_command_line_options_type_test.dart
test/compiler/does_not_support_invalid_environment_type_test.dart
test/compiler/does_not_support_invalid_option_test.dart
test/compiler/doesnt_support_invalid_type_for_boolean_option_test.dart
test/compiler/reports_dart_parse_errors_test.dart
test/transformer/a_transformer_rejects_its_config_test.dart
test/transformer/asset_not_found_exceptions_are_detectable_test.dart
test/transformer/can_log_messages_test.dart
test/transformer/fails_to_load_a_file_that_defines_no_transforms_test.dart
test/transformer/fails_to_load_a_non_existent_transform_test.dart
test/transformer/fails_to_load_a_pubspec_with_reserved_transformer_test.dart
test/transformer/fails_to_load_a_transform_from_a_deps_dev_dependency_test.dart
test/transformer/fails_to_load_a_transform_from_a_non_dependency_test.dart
test/transformer/fails_to_load_a_transform_with_a_syntax_error_test.dart
test/transformer/fails_to_load_a_transform_with_an_import_error_test.dart
test/transformer/fails_to_load_an_unconfigurable_transformer_when_config_is_passed_test.dart
test/transformer/prints_a_transform_error_in_apply_test.dart
test/transformer/prints_a_transform_interface_error_test.dart

Print a warning when running "pub build" and "pub serve"

---

lib/src/package_name.dart
lib/src/solver/failure.dart
lib/src/solver/package_lister.dart
lib/src/solver/version_solver.dart
test/version_solver_test.dart

Improve version solver output

---

doc/solver.md

Hi! 
not foo ^1.0.0
could mean two things: either “some foo, but not 1.*.*” or “foo 1.*.* is not selected”. I don’t know which meaning is correct, but I bet on the second one. Let’s clarify this in the docs?

Clarify the meaning of negative terms

---

lib/src/pubspec.dart
pubspec.yaml

Bump minimum SDK to one that includes List.cast

Stop using deprecated DelegatingList.typed

---

lib/src/http.dart
pubspec.yaml

We need the latest analyzer, front_end, and async to get past static
errors in these packages. Shelf needs to be updated to get the latest
async.
Fix a static error that is not caught by the analyzer around reassigning
the final `stackTrace` variable in a catch clause.

Fix parse errors with `--preview-dart-2`

---

lib/src/utils.dart
test/get/hosted/get_test.dart
test/get/path/nonexistent_dir_test.dart
test/global/activate/unknown_package_test.dart
test/hosted/fail_gracefully_on_missing_package_test.dart
test/version_solver_test.dart

I think this is a generally good change -- if you're piping to a file
or something, the word wrapping is probably just going to annoying. But
it also makes the tests less brittle to line wrapping differences.
In particular, some tests fail on Mac because the sandbox path lengths
are different, which in turn causes the output to word wrap differently.

Don't line wrap output if not connected to a terminal.

---

lib/src/sdk.dart
lib/src/sdk/dart.dart
lib/src/sdk/fuchsia.dart
lib/src/utils.dart
lib/src/validator.dart
lib/src/validator/dependency.dart
lib/src/validator/sdk_constraint.dart
test/deps_test.dart
test/lock_file_test.dart
test/pubspec_test.dart
test/sdk_test.dart
test/validator/dependency_test.dart
test/validator/sdk_constraint_test.dart
test/version_solver_test.dart

This also adds validation that requires an appropriate Dartk SDK
constraint in order for a package that has a dependency from the
Flutter SDK to be published.
Closes #1862

Add support for depending on packages from the Fuchsia SDK

---

lib/src/command/deps.dart
lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/package.dart

Manipulate executable paths only as paths

---

lib/src/sdk/flutter.dart
lib/src/sdk/fuchsia.dart
test/sdk_test.dart

This ensures that we don't fail with Flutter-related errors when
nothing depends on Flutter, even if FLUTTER_ROOT points to an invalid
directory.
Closes #1883

Lazily load Flutter's version

---

lib/src/sdk/dart.dart

Fixes https://github.com/dart-lang/pub/issues/

Use Platform.version for the SDK version

---

lib/src/http.dart

Previously, pub retried up to 5 times when it received a response with
HTTP status 502, 503, 504. This adds 500 to the list of retryable
response statuses.

Retry on pub server status 500

---

lib/src/package_name.dart
lib/src/pubspec.dart
lib/src/solver/package_lister.dart
lib/src/solver/reformat_ranges.dart
lib/src/solver/version_solver.dart
lib/src/utils.dart
lib/src/validator/sdk_constraint.dart
pubspec.yaml

This rewrites failures' incompatibility graphs so that they refer to
real version numbers rather than the pessimistic ranges that
pub_semver can now generate.
Note that this is expected to have one failing test until
dart-lang/pub_semver#30 lands and pub_semver 1.4.1 is released.

Support the latest pub_semver

---

lib/src/command/barback.dart
lib/src/command/build.dart
lib/src/command/serve.dart

Closes #1891
It's not possible to customize the `argParser` in a `Command` such that
it ignores these invalid options, instead customize the UsageException
to have the same message as running the command.
The difference now is that with arguments it will exit with code 64 and
without arguments it will exit with code 1.

Add back build/serve argparser options

---

lib/src/sdk/dart.dart

Follow-up to https://github.com/dart-lang/pub/commit/3d7ae0cdf0
Hopefully really fixes https://github.com/dart-lang/pub/issues/1887

Use Platform.version even when running from the repo

---

lib/src/global_packages.dart

Closes https://github.com/dart-lang/sdk/issues/33256
The details of variable expansion when setting the PATH variable are a
little hard to follow. `"$HOME"` should work in more places than `"~"`

Reference "$HOME" instead of "~" in PATH message

---

lib/src/command/run.dart
lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
lib/src/io.dart
lib/src/validator.dart
test/global/binstubs/outdated_snapshot_test.dart
test/global/binstubs/utils.dart
test/global/run/recompiles_if_snapshot_is_out_of_date_test.dart
test/global/run/runs_script_in_checked_mode_test.dart
test/test_pub.dart

This should fix https://github.com/dart-lang/sdk/issues/33577.
I discovered (after painful trial and error) that the tests for binstubs are basically broken. They don't run pub from its own repo and instead run the pub that's currently in the Dart repo where you invoked the Dart VM from. I left a comment to that effect, but I don't want to fix it now.
I did verify that this fixes the issue by:
1. Copying the latest pub over to the Dart SDK.
2. Then running these tests.

Look for the new snapshot error message from the Dart 2 VM.

---

doc/solver.md

In the simple error reporting example, root depends on `baz ^1.0.0`, not `baz ^3.0.0`. This PR fixes this lil typo.

Fix small typo in solver docs

---

lib/pub.dart
pubspec.yaml

Testing from kernel files saves time over testing from source. This does
not switch Travis to test this way yet, but adds the deps to make it
easier to use locally.
Add a non-src lib file so get better behavior out of the coarse module
strategy. Without this file every library ends up becoming it's own
module.

Add deps for testing with build_runner

---

lib/pub.dart
lib/src/entrypoint.dart
test/no_packages_dir_test.dart

Fixes #1951
Continues to allow _creating_ packages directories for now, but if they
exist and aren't being created they won't be touched.

Don't delete existing packages directories

---

lib/pub.dart

This library only exists to be an "entrypoint" in `lib/` rather than
`lib/src/` and allow all other files to get rolled up into a single
module. We don't publish this package anyway, but an `import` is more in
line with our intentions here than `export`.
See discussion in https://github.com/dart-lang/pub/pull/1955

Use an import for the module hack

---

test/validator/dependency_test.dart
test/validator/sdk_constraint_test.dart

According to the comment at `lib/src/validator.dart` lines 70-73 this
behavior was intended to change when the stable SDK was released, so
update the tests.

Update tests for SDK constraint validation

---

lib/src/command/lish.dart
lib/src/command/uploader.dart
lib/src/command_runner.dart
lib/src/exceptions.dart
lib/src/source/hosted.dart
test/lish/force_cannot_be_combined_with_dry_run_test.dart
test/pub_uploader_test.dart

If the environment variable does not have a scheme it will produce a
confusing error like `Bad state: Cannot use origin without a scheme`.
- Add a `ConfigException` to correspond to the config exit code.
- Change some non-reference usages of `[]` to backticks.
- Stop setting a default of the `server` option since it depends on user
config and could be incorrect. We never read the default value anyway
and now access of that field can throw and this would throw before
proper exception handling is set up.
- Attempt to parse the scheme when we read `PUB_HOSTED_URL` and throw a
more actionable exception when it is missing.
- Update tests hardcoding the usage string.

Add check for a scheme on PUB_HOSTED_URL

---

pubspec.yaml

Also add `publish_to: none` to document that this package will not be
published on pub, and consistently skip quotes for version strings which
don't need quotes.

Update to latest build_runner

---

test/oauth2/utils.dart
test/oauth2/with_a_server_rejected_refresh_token_authenticates_again_test.dart

This was rather consistently broken on travis. Probably because we were
not setting up the request handler in `authorizePub` before we called the
`redirect_uri`. Additionally, we never waited for the request to
`'/api/packages/versions/new'` to actually happen.

Fixed race conditions in test case.

---

lib/src/command/global_activate.dart
lib/src/global_packages.dart
test/global/activate/custom_hosted_url_test.dart
test/global/activate/custom_source_url_test.dart
test/package_server.dart

Proposed solution for #2039, looking for feedback on whether or not this would be an acceptable addition.
The solution ended up being very straightforward since pub already knows how to handle dependencies from custom hosted pub servers and activating a package globally is essentially just performing a `pub get` in a dummy package with a single dependency. All that was needed was a command-line flag to specify the custom pub URL that is then passed through to the `.refFor()` call used to build the dependency ref.
I went with `--source-url` for the CLI option mainly in an attempt to note its relation to `--source` while keeping it brief, but there may be a better name.
Additionally, since this flag is only applicable when activating from a hosted source, it might be worth failing if it is …

Add support for global activating package from a custom pub URL

---

lib/src/io.dart

This mitigates race conditions in which concurrent Pub processes "touch"
pubspec.lock at the same time and leave it with a trailing NUL character.
---
We've been seeing intermittent failures in our automated builds for some time now, which looked like this:
```
Error on line 1177, column 1 of pubspec.lock: Unexpected character.
^
```
However, we had a hard time tracking them down. Eventually, we determined that the unexpected character in that message was actually a NUL character.
"What was modifying `pubspec.lock` and adding a NUL character?" We weren't in our scripts, and there shouldn't be any reason for Pub to modify it since in all cases we've seen this issue, the pubspec.lock is checked in and didn't change after `pub get`.
However, looking at Pub's source, it looks like its `touch` …

Update last modified date directly in `touch`

---

lib/src/validator/name.dart
test/validator/name_test.dart

Fixes #2024
There is nothing that requires a library name to be a valid Dart
identifier, and it's common practices to at least have `part of` files
which include a `.` in the file name.

Remove validation for library file paths

---

lib/src/command_runner.dart

I just want to close: https://github.com/dart-lang/pub/issues/28

Fix #28 -- escaping arguments as mentioned in TODO

---

lib/src/command/uploader.dart
test/pub_uploader_test.dart

This was incorrectly removed in #1972. In the case of the `lish` command
the default was unused, but the `uplaoders` command still used it.

Restore default server for uploader command

---

doc/repository-spec-v2.md

This is an attempt to create a specification from our current behavior.
The server doesn't care about the `Accept` header, and does not send
the correct `Content-Type`. But the client seems to get this right,
and it doesn't seems to care about the response header.
This makes is clear what we can't change, and how to deal with
versioning if we decide to change something. I want to further
document what API end-points `pub.dartlang.org` offers and how
stable they are. This is just a first step in that direction, since
we're probably not going to able to change end-points required by
old pub clients.
Expanding this to cover publishing would be nice, but at the momement
the authorization scheme is hardcoded to use the Goolge OAuth flow
for all hosted pub servers, which is a security concern …

Outline for a minimal repository specification

---

lib/src/oauth2.dart
test/descriptor.dart

This ensures that we always have an email and a user_id / id_token
on the server.

Request openid and email scopes from oauth2

---

lib/src/validator/strict_dependencies.dart
test/validator/strict_dependencies_test.dart

Proposed fix of: https://github.com/dart-lang/pub/issues/1813

Don't validate imports in `example/` if it contains its own pubspec.yaml

---

lib/src/oauth2.dart
test/descriptor.dart

Now that we know this is the canonical scope, then let's use that.

Use canonical oauth2 scope for email

---

lib/src/source/hosted.dart

Just so that we don't forget why we didn't change this right now.

A note on why we're not using pub.dev/api

---

lib/src/dart.dart
test/validator/strict_dependencies_test.dart

The `analysis_options.yaml` is not part of the package.
It's for the editor, it should not affect which binaries are loaded
or how dependencies are analyzer when publishing.

Fix 2032, ignore analysis_options.yaml in pub

---

lib/src/source/hosted.dart

From reading through the code I think `_parseDescription.hashCode` was a possible typo and it was actually meant to be `description.hashCode`.
Should there be a corresponding test for this method?

return the hashCode of the description

---

lib/src/command/get.dart
lib/src/command/upgrade.dart

I think this documentation relates to when Dart 1.x when pub did more than
fetching dependencies and pre-compiling executables.
-----
Doing a bit of archaeology I find that it was introduced in c1405b945c6d818c8cfe78334e8d4b11fd913103 along with a similar phrase in documentation comment for `EntryPoint.acquireDependencies`, but this comment was removed by @natebosch in 5ca86eb6e7be45ade4e44cbb7402d296cdf8b32f which removed other Dart 1.x related features.
So I'm inclined to think this had to do with the code-transformer features in Dart 1.x.

Don't mention 'transformed dependencies'.

---

lib/src/validator/strict_dependencies.dart

Fixes #2204
The phrase "doesn't depend on" can be interpreted as "doesn't use" and
considered an unnecessary import. Rephrase to be more clear that the
message is discussing the dependencies in pubspec.yaml.

Rephrase warnings for missing deps

---

lib/src/command/get.dart
lib/src/command/run.dart
lib/src/command/upgrade.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
test/run/package_api_test.dart
test/run/runs_from_a_dependency_override_after_dependency_test.dart
test/snapshot_test.dart
tool/test.sh

And only precompile the single desired executable on `pub run`.
Following the suggestion from the discussion on https://github.com/dart-lang/pub/issues/1683#issuecomment-390717324 we avoid printing "precompiling executable..." on `pub run` if we don't have a terminal attached. That allows `pub run` to be used in scripts without polluting `stdout` but still explains the user where time is going on first run of eg. `pub run test`.
This PR does not change `pub global` behavior. We probably want to continue recompiling all executables on `pub global activate`.
This PR still allows --precompile for those who prefer the old behavior.

Don't precompile on pub get/upgrade by default

---

lib/src/io.dart
lib/src/source/hosted.dart
test/descriptor_server.dart
test/io_test.dart
test/package_server.dart

Fix 2 cases of `prefer_final_fields`. Fix some unnecessary_lambda
surfaced by making one field final.
Add a missing return on an argument to `List.map`.
Change the argument type on some utility methods to allow a function
returning `FutureOr` to avoid hints about missing returns on methods
expected to return a `Future`.

Fix existing hints and lints

---

lib/src/source/hosted.dart

The caller in `CacheListCommand.run` does not appear capable of handling
`null` values. Hence, filtering it out seems reasonable in this case.
Cherrypicking the minor fix from https://github.com/dart-lang/pub/pull/2270 onto master after landing https://github.com/dart-lang/pub/pull/2290

Filter out `null` from `getCachedPackages`.

---

lib/src/io.dart
lib/src/solver/version_solver.dart

The `.add` method returns a boolean indicating whether then value was
not already contained in the set. Find a few places where both are used
unnecessarily and refactor to only call `.add` and use the returned
boolean.

Refactor Set.add following !Set.contains

---

test/lock_file_test.dart
test/pubspec_test.dart

A Mock is an object that can record and verify interaction during a
test, these classes are not mocks.

Rename some test utilities from Mock to Fake

---

lib/src/io.dart

Use a conditional element in a List literal instead of conditionally
calling `.insert`. Change an implementation comment into an expanded doc
comment for handling the no-unknown-keyword argument.
Use a spread element instead of `..addAll`.

Use more collection literals for args

---

lib/src/system_cache.dart

Currently, the default location for pub's system cache is in %APPDATA%, which means it is in the roaming profile that gets synced across devices. This is less than ideal because it can get pretty large.
This PR moves the default location of the cache to %LOCALAPPDATA%, but will use %APPDATA% if the cache already exists there to avoid breaking existing installs linking to that location
Fixes #1273

Use LOCALAPPDATA for system cache on windows

---

lib/src/entrypoint.dart
lib/src/package_config.dart
test/descriptor.dart
test/package_config_file_test.dart

Instead of writing a language version based on the current SDK.
This causes the fallback to using the latest version to happen
at runtime instead of at `pub get` time.

Omit languageVersion when there is no SDK constraint

---

.travis.yml

Previously analyzer would report these but travis would pass anyway.

Fail travis for lints and warnings

---

.travis.yml
test/test_pub.dart
tool/test.sh

Testing `pub` without a snapshot is slow because many tests
invokes `pub` as a commandline tool. Supplying the snapshot
using a fixed filename is risky as it's easy to forget to
delete/rebuild the snapshot causing test results to be
out-of-date.
By using an environment variable to specify the name of the
`pub` snapshot, we can create a random temporary file for
each test run. This minimizes the risk that we accidentally
run tests with an outdated snapshot of `pub`.

Use a unqiue file name for the snapshot during testing.

---

lib/src/http.dart
test/hosted/fail_gracefully_on_url_resolve_test.dart

Do not retry on OS specific error codes for `SocketException`.
These OS error codes are not documented in the code, and they
may change behavior depending on OS and architecture.
Furthermore, many seemingly persistent errors such as DNS lookup
failures should be retried.
Finally, if we retry a `SocketException` unnecessarily this is of
little impact. It means that if the user doesn't have a network
connection, or tries to use a `PUB_HOSTED_URL` pointing to a
non-existent pub server, then it will take a bit longer before
the user is informed of the problem.

Retry on all SocketExceptions

---

lib/src/validator/pubspec_field.dart
test/lish/force_does_not_publish_if_there_are_errors_test.dart
test/lish/package_validation_has_an_error_test.dart
test/validator/pubspec_field_test.dart

Also validate the repository field.
This is intended to fix https://github.com/dart-lang/pub/issues/2312

Don't require homepage on `pub publish`

---

lib/src/command/lish.dart
lib/src/validator.dart
test/lish/force_publishes_if_there_are_warnings_test.dart
test/lish/preview_package_validation_has_a_warning_test.dart
test/test_pub.dart

```console
$ pub publish
Publishing watcher 0.9.7+13 to https://pub.dartlang.org:
|-- LICENSE
|-- README.md
'-- pubspec.yaml
Uploads to pub.dev are subject to https://pub.dev/policy
Do you want to publish watcher 0.9.7+13 (y/n)? n
Package upload canceled.
```
```console
$ pub publish
Publishing watcher 0.9.7+13 to https://pub.dartlang.org:
|-- LICENSE
'-- pubspec.yaml
Package validation found the following potential issue:
* Please add a README.md file that describes your package.
Uploads to pub.dev are subject to https://pub.dev/policy
Package has 1 warning. Do you want to publish watcher 0.9.7+13 (y/n)? n
```
**screenshot**
```console
[hack]$dart ../bin/pub.dart publish
Publishing test 1.0.0 to https://pub.dartlang.org:
|-- README.md
'-- pubspec.yaml
Package validation found the …
```

Pub publish dialog with policy link

---

lib/src/entrypoint.dart

* Documented the reasoning behind these assertions.
* Changed how we assert to forbid packages that are not in the
lockfile.

Change logic for asserting package_config.json is up-to-date.

---

pubspec.yaml

These were used for building pub when testing.
This is now done by tool/test.sh instead.

Remove unused dev_deps

---

lib/src/solver/report.dart
test/upgrade/renamed_package_circular_dependency.dart

The root package was not considered in the current set when calculating removed packages.
Fixes: https://github.com/dart-lang/pub/issues/2345

Fix reporting of removed packages

---

test/pub_test.dart
test/pub_uploader_test.dart

The `help` command i now hidden since it is redundant against the last
line which also explains how to use help.

Update usage output for latest args

---

lib/src/io.dart
test/test_pub.dart

This makes it more clear that `N` is the default if enter is pressed
with no value.

Capitalize the default in y/N prompt

---

lib/src/io.dart
lib/src/utils.dart

- `streamFirst` does not behave differently from `stream.first`. The
comment about being able to use it with single-subscription streams is
a lie.
- `streamLines` is redundant against `LineSplitter`.

Drop redundant stream utils

---

lib/src/oauth2.dart
lib/src/utils.dart

A Completer can be completed with a `Future` which matches the behavior
here, except in the case where we intentionally call `complete` late
because we may complete with a value or error in a different code path.
In this case we only ever complete with a value from one place.
Refactor to `async/await` in  `_authorize`.

Drop chainToCompleter util

---

lib/src/global_packages.dart
lib/src/utils.dart

This has been implemented in the SDK as `RegExp.escape`.

Drop quoteRegExp util

---

lib/src/command/global_run.dart
lib/src/command/run.dart
lib/src/executable.dart
lib/src/global_packages.dart
lib/src/isolate.dart

For fewer references to the legacy name and to match the option that
users would pass.

Rename arguments from checked to enableAsserts

---

doc/repository-spec-v2.md

In practice we don't need it as the list-versions API end-point already
returns an `archive_url`. If we switch clients to use this `archive_url`
we can easily change the URL that packages are downloaded from. Most
cases where a package has to be downloaded the client has to resolve
versions first, hence, we already have to call the list versions API. In
the rare cases where know what version we want, but we haven't done a
resolution this will cost us an extra round-trip, however, this seems
acceptable.
We are deprecating the end-point because we discovered that it was
conflicting with other end-points on `pub.dev`. Specifically,
`pub.dev/packages/<verion>` conflicts with
`pub.dev/packages/<version>.tar.gz` because a semver version number can
have a pre-release ending in `.tar.gz´. …

Deprecating the end-point for fetching package archives.

---

lib/src/command/outdated.dart
test/outdated/goldens/circular_dependencies.txt
test/outdated/outdated_test.dart

When root package is required by one of its dependencies, resolution
fails as the stripped `PubSpec` didn't retain the verion number.
This addresses this issue, and adds a test case covering circular
dependency on the root package.

Fix `pub outdated` for circular dependency on root.

---

lib/src/command/cache_repair.dart
lib/src/source/cached.dart
lib/src/source/git.dart
lib/src/source/hosted.dart

This makes `pub cache repair` a lot faster.
The max number of parallel downloads is still throttled to 16 by the ThrottleClient in `src/http.dart`.
I did not make the git cache repairs parallel as they are somewhat rarer (I expect).

Download hosted packages in parallel when repairing cache

---

lib/src/validator/language_version.dart

Fixes https://github.com/dart-lang/pub/issues/2397
During debugging, I noticed paths like this were flowing to getParsedUnit
```
/Users/kevmoo/github/json_serializable/json_serializable/./lib/builder.dart
/Users/kevmoo/github/json_serializable/json_serializable/./lib/type_helper.dart
/Users/kevmoo/github/json_serializable/json_serializable/./lib/json_serializable.dart
/Users/kevmoo/github/json_serializable/json_serializable/./lib/src/json_part_builder.dart
```
Adding `normalize` fixed this

Fix NPE during language version analysis

---

lib/src/validator/language_version.dart
pubspec.yaml

We want to change this API before we publish. The `languageVersion` API is deprecated in favor of this one as of https://dart-review.googlesource.com/c/sdk/+/140768

Use different language version API.

---

lib/src/command/outdated.dart
test/outdated/goldens/circular_dependencies.txt
test/outdated/goldens/mutually_incompatible.txt
test/outdated/goldens/newer_versions.txt

Small tweak to the heading/status for direct dependencies. WDYT @sigurdm ?

Small UI tweak

---

lib/src/command.dart
lib/src/command/deps.dart
lib/src/command/get.dart
lib/src/command/lish.dart
lib/src/command/upgrade.dart
lib/src/command_runner.dart

Since https://github.com/dart-lang/pub/commit/ab109723d9eb782c2ea4cce68c044da40403a652
we are seeing `install` and `update` in telemetry, which is weird. (These map to `get` and `upgrade` respectively.)
This commit ensures telemetry headers only see each command with its canonical name.

Normalize command names when invoked via alias

---

lib/src/command/outdated.dart
test/outdated/goldens/newer_versions.txt
test/outdated/outdated_test.dart

In the case we have a transitive dev_dependency in current, and a newer
exists it will have a 'latest' entry.
Fixes: https://github.com/dart-lang/pub/issues/2426

Fix output of transitive dev_dependencies

---

lib/src/command/outdated.dart
test/outdated/goldens/circular_dependencies.txt
test/outdated/goldens/dependency_overrides.txt
test/outdated/goldens/dependency_overrides_no_solution.txt
test/outdated/goldens/helptext.txt
test/outdated/goldens/mutually_incompatible.txt
test/outdated/goldens/newer_versions.txt
test/outdated/goldens/no_dependencies.txt
test/outdated/outdated_test.dart

Fix of https://github.com/dart-lang/pub/issues/2428
I have made the --help text be 80 columns.
@kwalrath The text and arguments has already changed quite a bit since the version you reviewed.
Could you look it through again?
I made a golden-file test of the help text, so we will notice changes.
The golden file (test/outdated/golden/helptext.txt) in this pr can be used for reviewing this.,
I have not changed how the defaults are printed as suggested in the issue.
The (default is on) comes from package:args. And if we want to change them, we should probably change them there. The 'default default' is off, so I guess that is why package:args doesn't print anything in that case.

Improve the `pub outdated --help` text

---

lib/src/io.dart
test/io_test.dart
tool/extract_all_pub_dev.dart

And stop using `tar` in streaming mode. It seems to give us problems.
Instead the decompressed tar file is stored to disk (that was always the
case on windows).
Also streamline the tar.gz extraction logic between
windows/non-windows a bit.
Has been tested with the tool/extract_all_pub_dev.dart tool on linux, and partial runs with windows and mac os.
Fixes: #2186 , https://github.com/dart-lang/pub/issues/2308

Use gzip decoder from dart:io.

---

lib/src/command.dart
lib/src/command/outdated.dart
lib/src/command_runner.dart

Specify the `usageLineLength` in our command and command runner. Use the
terminal width or default to 80 if it is unknown.
Remove a manually placed newline in a help string with a space so that
it can wrap based on terminal width. For a width of 80 the wrapping
matches the manual newline.

Use line length to wrap usage

---

lib/src/command/run.dart
test/run/v2/app_can_read_from_stdin_test.dart
test/run/v2/errors_if_only_transitive_dependency_test.dart
test/run/v2/errors_if_path_in_dependency_test.dart
test/run/v2/forwards_signal_posix_test.dart
test/run/v2/loads_package_imports_in_a_dependency_test.dart
test/run/v2/nonexistent_dependency_test.dart
test/run/v2/nonexistent_script_in_dependency_test.dart
test/run/v2/package_api_test.dart
test/run/v2/passes_along_arguments_test.dart
test/run/v2/runs_default_app_without_arguments.dart
test/run/v2/runs_from_a_dependency_override_after_dependency_test.dart
test/run/v2/runs_named_app_in_dependency_test.dart
test/run/v2/runs_named_app_in_dev_dependency_test.dart
test/run/v2/runs_shorthand_app_in_dependency_test.dart
test/run/v2/runs_the_script_in_checked_mode_test.dart
test/run/v2/runs_the_script_in_unchecked_mode_test.dart
test/test_pub.dart

@jwren, if the first argument given to `dartdev run` matches `[<package>[:<command>]]` where `<package>` is `[a-z_][a-z0-9_]*` and `<command>` is `[^/]+` then we forward to `pub run --v2` (as introduced here).
Long term, we have to find a way to embed this properly and move the entire _run_ related logic into a single place. Maybe `pub` just exports some functions for asserting that `pubspec.yaml` is installed, and what packages are installed, and whether they are immutable.. I don't think we have to clean this up for an MVP.

pub run --v2 for use in dartdev

---

lib/src/command/outdated.dart
lib/src/utils.dart

This should enable colors on common windows terminals.
Tested with cmd and powershell.

Rely on terminal telling if we can use colors

---

lib/src/command/outdated.dart
lib/src/utils.dart

Before colors would not be shown because they only get applied with a second level of terminal detection

Force colors in `pub outdated --color`

---

lib/src/command/run.dart

This is removing the fallback to `bin/main.dart` in `pub run --v2` as intended to be used for `dartdev run`, whenever, `dartdev run` gets arguments matching `[package[:command]]` (or no arguments at all).

Do not fallback to bin/main.dart

---

lib/src/global_packages.dart
test/global/activate/path_package_test.dart

We should never precompile dependencies of the activated package.
For path packages we also don't precompile the package itself
Fixes: https://github.com/dart-lang/pub/issues/2526

Don't precompile dependencies of global activate from path

---

lib/src/package_name.dart

Closes #2188
When the build system was a part of `pub` there was a concept of "magic"
packages that were always a dependency of any Dart package that
introduced additional constraints beyond those in the pubspec in order
to ensure that the runtime behavior of Transformers was supported by
that version of `pub`. After the build system was removed all the
"magic" constraints were removed but this code was left as unused
branches.
Remove the "isMagic" field and any references. Prune unreachable code
paths.

Drop the "magic" package concept

---

lib/src/command/outdated.dart
lib/src/language_version.dart
lib/src/null_safety_analysis.dart
lib/src/pubspec.dart
lib/src/solver/incompatibility.dart
lib/src/validator.dart
lib/src/validator/language_version.dart
lib/src/validator/null_safety_mixed_mode.dart
lib/src/validator/relative_version_numbering.dart
test/outdated/goldens/circular_dependencies.txt
test/outdated/goldens/dependency_overrides_no_solution.txt
test/outdated/goldens/mutually_incompatible.txt
test/outdated/outdated_test.dart
test/validator/null_safety_mixed_mode_test.dart
test/validator/relative_version_numbering_test.dart

https://github.com/dart-lang/pub/issues/2438

Warn about publishing in mixed mode

---

.github/move.yml

Configure the [GitHub move app](https://github.com/apps/move) so issues can be moved from the Flutter repo issue tracker (or any repo) to this repo.
Users with write access to the source repo and this repo will be able to use the Transfer Issue button:
Preferences copied from [dart-lang/sdk](https://github.com/dart-lang/sdk/blob/master/.github/move.yml).

Configure GitHub move app

---

test/get/path/absolute_path_test.dart
test/get/path/absolute_symlink_test.dart
test/get/path/empty_pubspec_test.dart
test/get/path/no_pubspec_test.dart
test/get/path/nonexistent_dir_test.dart
test/get/path/path_is_file_test.dart
test/get/path/relative_path_test.dart
test/get/path/relative_symlink_test.dart
test/get/path/shared_dependency_symlink_test.dart
test/get/path/shared_dependency_test.dart
test/get/switch_source_test.dart
test/list_package_dirs/ignores_updated_pubspec_test.dart
test/list_package_dirs/includes_dev_dependencies_test.dart
test/list_package_dirs/lists_dependency_directories_test.dart
test/list_package_dirs/lockfile_error_test.dart
test/list_package_dirs/missing_pubspec_test.dart
test/list_package_dirs/no_lockfile_test.dart
test/list_package_dirs/pubspec_error_test.dart
test/package_config_file_test.dart
test/packages_file_test.dart
test/sdk_test.dart
test/unknown_source_test.dart

Minor fixes to license headers which had 'd.file' instead of 'file'

Fixed license headers

---

test/validator/dependency_test.dart
test/validator/utils.dart

Package foo was published and broke our tests.
Took quite some time to figure out :)

Don't look for external package foo during testing

---

pubspec.yaml

That line sneaked in in https://github.com/dart-lang/pub/commit/04e0601eec2539156bfec7a74a2cc3828067c014

Remove unused dependency from pubspec.yaml

---

lib/src/command/outdated.dart
lib/src/log.dart
lib/src/utils.dart

Fixes: https://github.com/dart-lang/pub/issues/2607

Differentiate between ansi and unicode support

---

pubspec.yaml
test/run/enable_experiments_test.dart

Tests for pub will only ever be run on the latest dev release, so
no need to skip on previous SDKs

Fix experiments tests for Dart 2.11

---

test/test_pub.dart

Ensures better stack traces on failures

Use `await expectLater` in test helper

---

lib/src/command_runner.dart
lib/src/io.dart
lib/src/sdk/dart.dart
test/test_pub.dart

By inlining we can constant fold whether we are in a test or not.
Also removes some dead code.

Simplify test detection

---

lib/src/command/global_run.dart
test/global/binstubs/outdated_binstub_runs_pub_global_test.dart

Fixes https://github.com/dart-lang/pub/issues/2660

Don't show 'precompiling' from `global run` unless in terminal

---

.travis.yml

I believe `dart CLI` already knows about this: https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/src/analytics.dart#L126

Avoid manually disabling analytics on travis

---

lib/src/command/lish.dart
lib/src/command/uploader.dart
lib/src/source/hosted.dart
test/get/hosted/explain_bad_hosted_url_test.dart
test/lish/does_not_publish_if_private_with_server_arg_test.dart
test/lish/force_cannot_be_combined_with_dry_run_test.dart
test/pub_uploader_test.dart
test/test_pub.dart

This argument does not really work optimally.
This also fixes the error message given when
PUB_HOSTED_URL has a bad scheme.
Fixes: https://github.com/dart-lang/pub/issues/2695

Deprecate --server argument to `pub publish` and `pub uploader`.

---

lib/src/command_runner.dart

It caused breakage in `dart test` and `flutter pub`.
We considered testing for an environment variable that could be set up in the shell script starting pub in the sdk, but flutter invokes that same shell script.

Remove deprecation warning from pub top level.

---

lib/src/command/outdated.dart
test/outdated/goldens/helptext.txt

The `--transitive` option only affects the "human" report - so this should avoid some confusion.
Fixes: https://github.com/dart-lang/pub/issues/2737

Don't allow both `--json` and `--transitive`

---

lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
lib/src/lock_file.dart
test/downgrade/doesnt_change_git_dependencies_test.dart
test/get/git/check_out_and_upgrade_test.dart
test/get/git/check_out_revision_test.dart
test/get/git/check_out_test.dart
test/get/git/check_out_transitive_test.dart
test/get/git/check_out_twice_test.dart
test/get/git/check_out_unfetched_revision_of_cached_repo_test.dart
test/get/git/different_repo_name_test.dart
test/get/git/doesnt_fetch_if_nothing_changes_test.dart
test/get/git/lock_version_test.dart
test/get/git/locked_revision_without_repo_test.dart
test/get/git/stay_locked_if_compatible_test.dart
test/get/git/unlock_if_incompatible_test.dart
test/get/hosted/stay_locked_test.dart
test/global/run/package_api_test.dart
test/global/run/runs_script_without_packages_file_test.dart
test/must_pub_get_test.dart
test/run/dartdev/package_api_test.dart
test/run/package_api_test.dart
test/test_pub.dart
test/upgrade/git/do_not_upgrade_if_unneeded_test.dart
test/upgrade/git/upgrade_locked_test.dart
test/upgrade/git/upgrade_one_locked_test.dart
test/upgrade/git/upgrade_to_incompatible_pubspec_test.dart
test/upgrade/git/upgrade_to_nonexistent_pubspec_test.dart

Pub will still create .packages, but no longer rely on it being there.
Fixes: https://github.com/dart-lang/pub/issues/2762

Stop depending on .packages

---

lib/src/command/add.dart
lib/src/command/remove.dart

Fix case where `pub remove foo --dry-run` might update `PUB_CACHE/global_packages/`
I'm not entirely sure what happens here.. But I think think we are abusing the `Entrypoint.global`
constructor to produce the same output from `--dry-run` as you would get from mutating the
pubspec and running `Entrypoint.acquireDependenices`.

Fix pub remove --dry-run

---

lib/src/package.dart
lib/src/pubspec.dart
lib/src/validator.dart
lib/src/validator/flutter_constraint.dart
pubspec.yaml
test/get/flutter_constraint_upper_bound_ignored_test.dart
test/must_pub_get_test.dart
test/pubspec_test.dart
test/validator/flutter_constraint_test.dart

Ignore any flutter sdk upper bound when parsing `pubspec.yaml`s.
Warn about the flutter sdk upper bounds before publishing.
We need a better url to point to.

Deprecate flutter constraint upper bound

---

lib/src/solver/package_lister.dart
lib/src/source.dart
lib/src/source/cached.dart
lib/src/source/path.dart
lib/src/source/sdk.dart
lib/src/source/unknown.dart

This has not been used since the old packages/ folder was retired.

Remove unused function

---

lib/src/command.dart

Fixes: https://github.com/dart-lang/pub/issues/2792
By always asking for `dart pub --trace` we should get correct reproduction of both `flutter pub` and `pub` toplevel commands, even though the command looks different. (the `dart` executable in flutter/bin will set the FLUTTER_ROOT variable leading to the right behaviour.).

Fix reproduction command

---

lib/src/global_packages.dart
lib/src/lock_file.dart
test/global/activate/activate_hosted_twice_test.dart

Fixes: https://github.com/dart-lang/pub/issues/2791
Note that we re-precompile if anything in the resolution changed.
There will still be some time spent for doing version resolution, but I suspect that is unavoidable.
This makes it slightly harder to force a recompile in case something goes wrong. But there's still 'deactivate followed by activate'.
This is a bit hacky.
Ideally we would like to align repeated `pub global activate` with `pub upgrade --precompile` and have the no-op detection in a common path. That will probably be a bigger change though.

Don't reprecompile if current global installed was same version

---

lib/src/entrypoint.dart
lib/src/lock_file.dart
lib/src/packages_file.dart
pubspec.yaml
test/descriptor/packages.dart

We only used it for writing/reading .packages files, and that was
deprecated.
At some point we stop generating/reading those files. At that point
this code can be removed.
Fixes: https://github.com/dart-lang/pub/issues/2820

Inline all usage of package:package_config

---

lib/src/entrypoint.dart
lib/src/package.dart
lib/src/package_config.dart
test/must_pub_get_test.dart

Fixes: https://github.com/flutter/flutter/issues/73870
Fixes: https://github.com/dart-lang/pub/issues/2806
This is somewhat a hack but should solve the immediate issue. It would be desirable to have 
* Flutter not rely on this by generating to a synthetic package
* Some well-defined mechanism for referring to synthetic code in a specific location.

Allow package_config.json to contain flutter_gen

---

lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/io.dart
lib/src/rate_limited_scheduler.dart
lib/src/solver/report.dart
lib/src/solver/result.dart
lib/src/source.dart
lib/src/source/hosted.dart
test/add/common/invalid_options.dart
test/descriptor_server.dart
test/get/hosted/warn_about_discontinued_test.dart
test/hosted/offline_test.dart
test/package_server.dart

The responses from the version listings are cached in the pub cache, such that we don't have to re-query the server on a `pub get` where pubspec.lock already exists and the packages are in cache already.
The cached responses are stored as a json:
```
{
...<body>
"_fetchedAt": Iso8601String
}
```
The cached file will be at `<PUB_CACHE>/hosted/<url>/.cache/<package-name>-versions.json`
where body is the decoded response from the server.
This gives a maximum delay of the discontinued warning of 3 days from the actual discontinuation.
To see if a cached response is too old we both check the file modified timestamp (for speed) and the json timestamp (for extra robustness).
One hope is that the cached responses can be used for speeding up `pub get` itself, if/when we have a faster way of …

Warn about discontinued packages on pub get/upgrade

---

lib/src/http.dart
test/hosted/metadata_test.dart
test/test_pub.dart

Follow up from https://github.com/dart-lang/pub/pull/2759, I think it's fair that we send no metadata when `CI=true`.

No metadata when CI=true

---

lib/src/command/outdated.dart
test/outdated/goldens/handles_sdk_dependencies.txt
test/outdated/goldens/ignores_sdk_dependencies.txt
test/outdated/goldens/newer_versions.txt
test/outdated/outdated_test.dart

Mention the source of non-hosted package-versions.
Fixes: https://github.com/dart-lang/pub/issues/2832

Show outdated sdk packages.

---

lib/src/http.dart
lib/src/io.dart

Running `dart pub get --verbose` in `flutter/gallery` shows:
```
IO  : Get versions from https://pub.dartlang.org/api/packages/url_launcher_platform_interface.
IO  : HTTP GET https://pub.dartlang.org/api/packages/url_launcher_platform_interface
| Accept: application/vnd.pub.v2+json
| X-Pub-OS: linux
| X-Pub-Command: upgrade
| X-Pub-Session-ID: 80D86525-9A4A-4468-AE49-23A6725FA366
| X-Pub-Reason: direct
| user-agent: Dart pub 2.12.0-248.0.dev
```
That's a problem... looking at the code it seems setting `dependencyType.none` does not override existing `dependencyType` in the current zone.
This has been causing issues since we introduced prefetching in Dart 2.8.
----------------
TL;DR: Dependency-type `direct` cannot be trusted since Dart 2.8.

Fix request metadata when overriding dependencyType

---

lib/src/command/downgrade.dart

Downgrade was introduced here: https://codereview.chromium.org//365993007
And it seems there was always a call to `saveLockfile()`.
Not saving the lockfile would also lead pub to complain when doing `pub run`.

Downgrade actually modifies `pubspec.lock`

---

lib/src/io.dart
pubspec.yaml
test/io_test.dart

Uses `pkg:tar` to read and write tar files. That package is based on stream transformers and generally tries to minimize memory overhead. It supports the ustar format and extended PAX headers.
For testing, I ran `tool/extract_all_pub_dev.dart`, but only with the latest version of each package. To test backwards-compatibility, I published some packages with `pkg:tar` to a personal pub server and downloaded them with the regular pub on Linux and Windows. I don't have access to a Mac, but I can run more tests on the other OSes if needed.
Full disclosure: I wrote the tar package. 
Closes #1602 (and a bunch of related issues).

Use Dart library to read and write tar files

---

lib/src/command/outdated.dart
lib/src/command_runner.dart
test/outdated/goldens/bad_arguments.txt
test/outdated/goldens/no_pubspec.txt
test/outdated/outdated_test.dart

Also fixes an issue where stack traces would be exposed to the user in case of some parsing errors (when using the `pub` binary - I don't think this happens with `dart pub`.
Fixes: https://github.com/dart-lang/pub/issues/2868

Don't allow outdated taking arguments

---

lib/src/utils.dart

isTravis would only return true on Travis and pub no longer uses Travis.

Remove unused field

---

lib/src/command.dart
lib/src/command/add.dart
lib/src/command/deps.dart
lib/src/command/downgrade.dart
lib/src/command/get.dart
lib/src/command/lish.dart
lib/src/command/list_package_dirs.dart
lib/src/command/outdated.dart
lib/src/command/remove.dart
lib/src/command/run.dart
lib/src/command/upgrade.dart
lib/src/command/uploader.dart
lib/src/command_runner.dart
lib/src/entrypoint.dart
lib/src/pub_embeddable_command.dart
lib/src/solver/report.dart
test/directory_option_test.dart
test/embedding/goldens/helptext.txt
test/goldens/directory_option.txt
test/lish/force_cannot_be_combined_with_dry_run_test.dart
test/outdated/goldens/bad_arguments.txt
test/outdated/goldens/helptext.txt
test/outdated/goldens/no_pubspec.txt
test/outdated/outdated_test.dart
test/pub_uploader_test.dart
test/run/dartdev/errors_if_path_in_dependency_test.dart
test/run/errors_if_no_executable_is_given_test.dart
test/run/errors_if_path_in_dependency_test.dart
test/test_pub.dart

Fixes: https://github.com/dart-lang/pub/issues/2864

Add --directory option

---

lib/src/command/lish.dart
test/goldens/directory_option.txt
test/lish/dry_run_warns_about_server_checks.dart

This somewhat improves the situation of: https://github.com/dart-lang/pub/issues/2828

`publish --dry-run` informs that the server might do more checks

---

lib/src/command/cache.dart
lib/src/command/cache_clean.dart
test/cache/clean_test.dart

Fixes: https://github.com/dart-lang/pub/issues/2521
We could consider letting the command only delete some files (for example leaving credentials.json), but I'm not sure the complexity is worth it - it is not that hard to log in again.

`cache clean`

---

lib/src/command/outdated.dart
test/outdated/goldens/null_safety_already_migrated.txt
test/outdated/outdated_test.dart

The `pub outdated --mode=null-safety` command gives confusing comments for packages that are already null safe. I have added a message i.e. `All dependencies opt in to null-safety.` in a case when there are no dependencies shown inside the table. 
Fixes #2745 
@sigurdm PTAL and suggest changes if any.

pub outdated: added clear message for null safe packages

---

lib/src/solver/report.dart
lib/src/solver/result.dart
test/upgrade/dry_run_does_not_apply_changes_test.dart
test/upgrade/report/describes_change_test.dart

I have added a message showing the number of discontinued packages for pub upgrade command.
Fixes #2865

pub upgrade command to show number of discontinued packages

---

lib/src/io.dart

This shouldn't have any side-effect, as nobody is calling without `baseDir`, this just stops people from using said footgun in the future.

Minor cleanup to reduce risk of using path.current

---

lib/src/command/add.dart
test/add/common/add_test.dart

Added usage exception if extra arguments are passed.
Fixes #2923 
cc @sigurdm @jonasfj 
I am bit unsure whether to put the test case into `add_test.dart` or `invalid_options.dart`. So, as of now it's in `add_test` let me know if its needs to be changed.

Add command to fail if extra arguments are passed

---

lib/src/http.dart
lib/src/io.dart
lib/src/source/hosted.dart
test/get/hosted/get_stress_test.dart

Rolling `pub` into the Dart SDK was reverted, due to an intermittent failure.
I dug into it, and found that `pub get` fails to fetch all dependencies if there is more than 16.
I'm not exactly sure what is going on, I suspect we got some concurrency wrong.
Probably because we don't allow more than 16 concurrent downloads.
Still not sure what caused the queuing to not work as it used to, it's not like we changed anything there.
This PR adds a test that `pub get` can fetch more than 16 dependencies. That's always nice to test, especially when 16 is a magic number wrt. to limiting concurrent downloads.
Culprit from `git bisect`.
```
9a70949e25e9407423c68af5aed0f52b0655fe09 is the first bad commit
commit 9a70949e25e9407423c68af5aed0f52b0655fe09
Date:   Fri Feb 5 13:51:03 2021 +0100
Use Dart …
```

Handle package:tar cancellations

---

.github/workflows/test.yaml
lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
pubspec.yaml

Opening for discussion, I wanted to try this out to see if we can speed up the rebuilds of pub executables - it does appear to be much faster (basically immediate if there is no change).  Surprisingly, it is almost twice as fast on the initial precompile as well for me. I think that probably means that the vm snapshot functionality is doing something additional - I don't know what the implications of using kernel instead might be.
Specifically this:
- Creates a new dir `.dart_tool/pub/incremental` where it stores the previous dill outputs for each executable.
- Uses the frontend server to compile to that directory (which will use those files automatically to initialize from).
- Copies the output from there to the actual executable path if successful.
Previous snapshot behavior:
New fe …

Use the frontend server to compile pub executables

---

lib/src/validator/gitignore.dart

```
1 checked in file are ignored by a `.gitignore`.
```
(OLD) vs (NEW)
```
1 checked in file is ignored by a `.gitignore`.
```

fix grammar in .gitignore error message

---

lib/src/global_packages.dart

Fixes https://github.com/dart-lang/pub/issues/3000, downside is that if you want to downgrade from Dart 2.14.x to Dart 2.9.x, then packages activated with `dart pub global activate <package>` won't work anymore.
Upside is that now `dart pub global activate <package>` will work for users who have installed Dart from the Flutter SDK.
----
It's still be messy if you have two Dart SDK installations as Flutter in some configurations still use a different `PUB_CACHE`.

New binstubs for global activate using `dart pub`

---

.github/workflows/test.yaml
lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
pubspec.yaml

Reverts dart-lang/pub#2968, @jakemac53 apparently we don't have `frontend_server_client` in the Dart SDK :see_no_evil: 
I'm reverting this for now, so I can merge and land other fixes.

Revert "Use the frontend server to compile pub executables"

---

analysis_options.yaml
lib/src/io.dart
lib/src/third_party/tar/README.md
lib/src/third_party/tar/src/reader.dart
lib/src/third_party/tar/src/writer.dart
lib/src/third_party/tar/tar.dart

- Upgrades tar (the changes have been reviewed by @jonasfj)
- Use the gnu style format in the tar writer
- Exclude tar sources from lints in this package
Closes #3001

Generate GNU-style long file names in tar archives

---

lib/src/package.dart

Make `.gitignore` and `.pubignore` case-insensitive on Windows / MacOS

---

lib/src/ignore.dart
test/ignore_test.dart

Fixing #3003, apparently it seemed we weren't parsing CR LF in `.gitignore`,
which caused patterns to mismatch on Windows.

Fix CR LF in .gitignore / .pubignore

---

test/lish/does_not_include_dot_file.dart

All other tests files contains `@dart=2.10` annotation expect does_not_include_dot_file.dart file.

Downgraded does_not_include_dot_file.dart to 2.10

---

lib/src/command/global_activate.dart
lib/src/command/lish.dart
lib/src/global_packages.dart
lib/src/source/hosted.dart
lib/src/validator.dart
lib/src/validator/relative_version_numbering.dart
test/get/hosted/explain_bad_hosted_url_test.dart
test/hosted/fail_gracefully_on_invalid_url_test.dart
test/hosted/will_normalize_hosted_url_test.dart
test/validator/relative_version_numbering_test.dart
test/version_solver_test.dart

Fixes https://github.com/dart-lang/pub/issues/3024
We normalize the URL for a _hosted pub server_ to have no slash if the
server is just a bare domain like `https://example.com`, but if the URL
contains a path like `https://example.com/my-folder` then we always
normalize to `https://example.com/my-folder/`.
The reason for normalizing the URL is to improve consistency in
`pubspec.lock` and make it easier to implement authentication without
risks of being tricked by incorrect prefixes.
Additionally, be normalizing to no slash for empty paths, and paths
always ending in a slash when path is non-empty, we gain the benefit
that relative URLs can always be constructed correctly using
`hostedUrl.resolve('api/packages/$package')`.
This additionally forbids a few edge cases such as:
* querystring …

Validate and normalize hosted url.

---

lib/src/sdk/flutter.dart
test/sdk_test.dart
test/version_solver_test.dart

Fix https://github.com/dart-lang/pub/issues/2307, tested on Windows and Linux using a few hacks.
If the Dart SDK is present inside the Flutter SDK in sub-folder
`bin/cache/dart-sdk/`, then we no-longer require the environment
variable `FLUTTER_ROOT` to be specified. Instead we simply derive
the location of the Flutter SDK from the location of the Dart SDK.
We still allow the environment variable `FLUTTER_ROOT` to override
the otherwise automatically detected Flutter SDK location.

Detect Flutter SDK location relative to Dart SDK

---

lib/src/source/git.dart
test/get/git/path_test.dart

Sometimes they would be handled as local file-paths leading to broken behviour.
Fixes: https://github.com/dart-lang/pub/issues/3012

Use uris for paths in git source descriptions

---

lib/pub.dart

This will allow the dart command to expose the exact command - which can then be forwarded to by the `pub` script in the sdk removing the need for a separate snapshot.

Expose the pub top-level as a command

---

lib/src/command/run.dart

I believe "instead" should be outside of the quotation.
> Use `dart run instead`
> Use `dart run` instead.

Fix a typo

---

tool/test.dart

This updates the `tool/test.dart` script to do incremental compilation of the `bin/pub.dart` script using the utilities already available in pub.
This makes running tests using `tool/test.dart` significantly faster - since we get incremental builds of pub itself.

use incremental compilation in the tool/test.dart script

---

lib/src/package_name.dart
test/version_solver_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3057
Fixes: https://github.com/dart-lang/pub/pull/3038
Fixes: https://github.com/dart-lang/pub/issues/3028
I am not sure what was exactly meant by having the case `(range.min.isPreRelease && range.max == range.min.nextBreaking)` but it seems not. quite right. 
`>=0.9.0-1 < 0.10.0` would get translated to `^0.9.0-1`. But `^0.9.0-1` in pub_semver is the same as `>=0.9.0-1 < 0.10.0-0`, and that is what gets captured by the first part of the condition: `range.max == range.min.nextBreaking.firstPreRelease`.

Fix broken simplification of prerelease constraints

---

.gitallowed
lib/src/ignore.dart
lib/src/pubspec.dart
lib/src/validator.dart
lib/src/validator/leak_detection.dart
lib/src/validator/pubspec_typo.dart
test/ignore_test.dart
test/validator/leak_detection_test.dart

Inspired by the paper [How Bad Can It Git?][1] the
`LeakDetectionValidator` uses regular expressions and entropy thresholds
to scan files for possible secrets about to be published. If files about
to be published matches any of the patterns for known secret keys an
error is thrown and the publishing event is aborted.
To ignore a _false-positive_ a `false_secrets` field is introduced in
`pubspec.yaml`. This field is a list of git-ignore style patterns for
files to ignore when scanning for potential leaks. This allows package
authors to explicitly ignore files known to contain _false positives_.
This commit includes API keys and secrets from various systems, these
have all been revoked immediately following creation and included for
testing and entropy threshold computation.
-------
This …

Detect potential leaks in `dart pub publish`.

---

test/test_pub.dart
tool/test.dart

* Prints the failure message when the snapshot fails to compile
* Runs the test-runner in ProcessStartMode.inheritStdo for nicer interactive behavior.
* Uses `dart run test`, rather than `pub run test` to invoke the runner.
It seems the runner changed how tests are invoked, they are no longer a `data` url. Therefore I made the simplifying assumption that tests always should be invoked from the pub directory.

Improve test script

---

lib/src/validator/strict_dependencies.dart
test/validator/strict_dependencies_test.dart

I saw this error today `* line 7, column 1 of test/dynamic_colors_plugin_test.dart: This package does not have meta in the dependencies section of pubspec.yaml.`, which isn't quite accurate. 
This PR differentiates the case when a dependency should be added to `dependencies` from the case where it should be added to either `dependencies` or `dev_dependencies`.
There are no tests currently checking the error message, but I could add a couple if needed.

Tweak strict dependencies error message for `_validateBenchmarkTestTool`

---

test/deps/executables_test.dart
tool/test.dart

Followup to https://github.com/dart-lang/pub/pull/3091
Fixes two things that would fail when the tests were run interactively:
* The tool/test.dart script would hang listening for signals. Cancelling the subscription seems to work.
* A single test would call the tree-drawing code and get colors because we inherit the stdio. Strip those colors.

More tool/test.dart tweaks

---

lib/src/global_packages.dart
test/global/binstubs/binstub_runs_executable_test.dart
test/global/binstubs/runs_once_even_when_dart_is_batch_test.dart

~~In the Batch file defined in `_createBinStub`, the script attempts to call the package using the dart snapshot. If it fails, the Batch script uses `dart pub global` directly. However, the `dart pub global` command is still present even when using the snapshot works. This PR removes the second call so that package is only run once. This is especially important/urgent because a lot of executable packages focus on project management, and make sensitive changes to the files in a user's project. Having those changes run twice can cause errant behavior.~~
**EDIT**: Adding a `call` before the dart command in the generated binstub fixes an error where, if the user has `flutter\bin\dart.bat` ahead of `flutter\bin\cache\dart-sdk\bin\dart.exe` in their PATH, the script gets called twice. I tried …

Remove duplicate global invocation on Windows

---

lib/src/package.dart
test/package_list_files_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3102
We are still not taking all the same gitignores as git would into account (eg. https://stackoverflow.com/a/5724484) but this is hopefully good enough.

Use ignore files up to git root

---

doc/repository-spec-v2.md
lib/src/source/hosted.dart

* Documented authentication with `dart token add <hosted-url>`
* Documented publishing with `dart pub publish`
* Clean-up language centering on `<hosted-url>` and "package repository"
* Removed discussion of meta-data only specific to `pub.dev`
* Mentioned `hosted` in `pubspec.yaml`
* Added notes on temporary URL usage and leavering GCS, S3 or similar blob storage service.
/cc: @isoos, @themisir, please see if you agree with this characterization of the repository specification.

Update the repository specification

---

lib/src/ascii_tree.dart
lib/src/dart.dart
lib/src/exceptions.dart
lib/src/io.dart
lib/src/log.dart
lib/src/progress.dart
lib/src/sdk.dart
lib/src/sdk/dart.dart
lib/src/sdk/flutter.dart
lib/src/sdk/fuchsia.dart
lib/src/solver/version_solver.dart
lib/src/utils.dart
test/ascii_tree_test.dart
test/error_group_test.dart
test/transcript_test.dart
test/utils_test.dart

I couldn't stop myself... let's see if tests pass... We should probably move to `package:yaml_edit` and migrate `ignore.dart` next...
After that I think it's going to be hard to identify things we migrate alone.

Migrate utils and dependencies to null-safety

---

lib/src/feature.dart
lib/src/lock_file.dart
lib/src/pub_embeddable_command.dart

Fixes analyzer warnings that causes CI pipeline to fail:
```
Run dart analyze --fatal-infos
Analyzing pub...
info - lib/src/feature.dart:7:8 - The import of 'dart:collection' is unnecessary as all of the used elements are also provided by the import of 'package:collection/collection.dart'. Try removing the import directive. - unnecessary_import
info - lib/src/lock_file.dart:7:8 - The import of 'dart:collection' is unnecessary as all of the used elements are also provided by the import of 'package:collection/collection.dart'. Try removing the import directive. - unnecessary_import
info - lib/src/pub_embeddable_command.dart:8:8 - The import of 'command.dart' is unnecessary as all of the used elements are also provided by the import of 'command.dart'. Try removing the import directive. - …
```

Fix analyze errors

---

lib/src/package_name.dart
test/sdk_test.dart
test/version_solver_test.dart

- reduces cross-linking a slight bit
- future-proofing new sources

Use source.hasMultipleVersions to decide when to show version constraint.

---

lib/src/package.dart
test/package_list_files_test.dart

Fixes:  https://github.com/dart-lang/pub/issues/3152
The issue was that we have a legacy ignore rule (always ignore folders named `packages`. After we started interpreting gitignores from the git-root we would no longer venture into `packages/url_launcher` at all.
We should consider if we want to keep the legacy rule. Dart has not created packages/ for a loong time - and it is a pretty generic name bound to come up somewhere else.

Don't ignore 'packages/' over the root-dir

---

lib/src/pubspec.dart
lib/src/pubspec_parse.dart

- code blocks have been moved unchanged + minimal update to become null-safe
- the rest of `Pubspec` depends more on other parts of the `pub` client, and requires change in the initialization and/or code structure, doing them in follow-up PRs

Extract some parts of pubspec parsing to a null-safe library.

---

lib/src/validator/gitignore.dart
test/validator/gitignore_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3172

Gitignore validator should not follow symlink dirs

---

lib/src/command/token_add.dart
lib/src/io.dart

Piping `stdin` to a `LineSplitter` and then using a `StreamQueue` causes
event handler to wait for next characters after a line has been read.
Hence, if we don't `exit()` explicitly or hit `stdin.close()` then the
process will hang waiting for input on `stdin`.
Using `stdin.readLineSync()` alleviates this issue. Having a timeout on
prompts for tokens is nice, but only really required if we prompt while
the solver is running. Which we probably won't need to do anyways, so
not having a timeout is likely fine.
---------------------
This should be cherry-picked for 2.15, I manually checked `tool/test-bin/pub_command_runner.dart pub token add` and `tool/test-bin/pub_command_runner.dart pub publish` against master, and this seems to fix the issue.

Fix hanging event handler for `stdin`.

---

doc/repository-spec-v2.md

I figured these links might be useful to the reader.

More links in the repository specification

---

lib/src/command/cache_repair.dart
lib/src/io.dart
lib/src/source/hosted.dart

Fixes: https://github.com/dart-lang/pub/issues/1178
The basic idea is that if two pub processes are in a race to install a package-version, we let the first one win, and just ignore the failure to install the second one.

Avoid race condition for hosted source on package extraction

---

lib/pub.dart
lib/src/pub_embeddable_command.dart
test/embedding/embedding_test.dart
tool/test-bin/pub_command_runner.dart

Fixes: https://github.com/dart-lang/pub/issues/3272
When this is rolled in the embedder can provide an `isVerbose` to enable this:
```
$ dart --verbose pub get
```

Fix --verbose doc, and accept verboseness setting from embedder

---

lib/src/command/add.dart
lib/src/language_version.dart
lib/src/source/hosted.dart
test/add/common/add_test.dart
test/add/git/git_test.dart
test/add/hosted/non_default_pub_server_test.dart
test/add/path/absolute_path_test.dart
test/testdata/goldens/help_test/pub add --help.txt

With reference to issue #3273 
I've added support for multiple packages for  ```dart pub add``` command.
It supports multiple packages from default host and custom hosts but only one package for one git repository.
It could be really useful during copy/pasting from articles and tutorials.
I used a loop for parsing each argument into a package and then adding them to the pubspec.yaml in memory.
The I used a loop for verifying the results of each package and then writing to the pubspec.yaml file.
I also added tests to verify the feature.

Support multiple packages in 'dart pub add'

---

lib/src/ignore.dart
test/package_list_files_test.dart

fixes handling of  statements that should be handled against directory of "ignore" file
quote from https://git-scm.com/docs/gitignore#_pattern_format
> - The slash / is used as the directory separator. Separators may occur at the beginning, middle or end of the .gitignore search pattern.
> 
> - If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

fix: relative to the current directory rules

---

lib/src/third_party/tar/README.md
lib/src/third_party/tar/src/constants.dart
lib/src/third_party/tar/src/entry.dart
lib/src/third_party/tar/src/reader.dart
lib/src/third_party/tar/src/utils.dart
lib/src/third_party/tar/src/writer.dart
lib/src/third_party/tar/tar.dart
test/io_test.dart

This upgrades the vendored `tar` package from https://github.com/simolus3/tar/commit/b5c5a11d8969f458ccdeb8cf01615f692fed3e97 to https://github.com/simolus3/tar/commit/ce8aae4825ac4cbed80829cd0d6e181b924b3db2.
Noteworthy changes in `package:tar`:
- Decode tar archives with malformed UTF-8 data in non-important PAX headers.
- Forward pause/resume requests when writing tar streams.
- Use a faster, tar-specifc implementation to split the input stream into suitably-sized blocks.
- Support writing tar entries synchronously.
- Faster checksum implementation.
- Avoid copying when reading old GNU sparse maps.
Overall, I expect that these changes will improve the performance of extracting or archiving packages. Quite a bit has changed between the two versions though, so maybe we should once again …

Upgrade `package:tar` to version `0.5.4`.

---

lib/src/command/lish.dart
lib/src/source/hosted.dart
test/lish/archives_and_uploads_a_package_test.dart
test/test_pub.dart
test/token/token_authentication_test.dart
test/token/when_receives_401_removes_token_test.dart
test/token/when_receives_403_persists_saved_token_test.dart

This refactors testing of publishing a bit... and allows use of `dart pub token add` when talking to `pub.dartlang.org`.

Allow use of token for talking to pub.dev

---

lib/src/git.dart
lib/src/validator/gitignore.dart
test/get/git/git_not_installed_test.dart
test/test_pub.dart
test/validator/gitignore_test.dart

The gitignore validator is only a warning, its failure to run git should not prevent publication.
This is a followup to: https://github.com/dart-lang/pub/pull/3332

Avoid failing in gitignore validator

---

lib/src/source/path.dart
test/get/path/relative_path_test.dart

This broke in https://github.com/dart-lang/pub/pull/3305

Always use forward slash for relative paths in lockfile

---

test/get/with_empty_environment_test.dart
test/test_pub.dart
test/token/add_token_test.dart
test/token/remove_token_test.dart
tool/test.dart

This was triggered by spending time not understanding why tests failed when run with dart from a flutter checkout.
They will still not run with a dart from a flutter checkout (but you'll get a warning).
However in my opinion it is still preferable that tests are not affected by the environment.
We need to pass HOME for the .config stuff - we could also consider making a homedir in the sandbox....
We need to pass PATH for enabling use of the system git.

Make tests more agnostic to the test environment

---

doc/repository-spec-v2.md

Fixing link example "User-Agent" in doc/repository-spec-v2.md

---

lib/src/command/add.dart
test/add/common/add_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3421
We cannot use `wrapYamlNode({}, collectionStyle: CollectionStyle.BLOCK)`, as the empty map can only have the flow style.

`pub add` create top-level attribute in block-style if possible.

---

lib/src/command/login.dart

Fix #3424 .
The PR #3427 only fix the dart error. But actually pub cannot retrieve the user info. 
As @bsutton said.
> The symptom is that the 'name' field is not being returned by the google auth mechanism.
> I've tried pub logout and then pub login with the same results.
> Is there some chance that google no longer return the 'name' field in the user info response?
> 
> Reading the google documentation:
> https://developers.google.com/identity/protocols/oauth2/openid-connect#server-flow
> name - The user's full name, in a displayable form. Might be provided when: The request scope included the string "profile"
> The ID token is returned from a token refresh. When name claims are present, you can use them to update your app's user records. 
> 
> Note that this claim is never guaranteed …

Make `name` field of `_UserInfo` nullable. Fix #3424

---

lib/src/third_party/tar/README.md
lib/src/third_party/tar/src/charcodes.dart
lib/src/third_party/tar/src/constants.dart
lib/src/third_party/tar/src/entry.dart
lib/src/third_party/tar/src/format.dart
lib/src/third_party/tar/src/header.dart
lib/src/third_party/tar/src/sparse.dart
lib/src/third_party/tar/src/utils.dart
lib/src/third_party/tar/tar.dart

The only non-trivial change is that the reader now handles pause events happening after the last chunk of a tar entry but before the stream is fully closed.
I don't believe these changes to have an impact on pub, but if you want me to I can once again setup a comparison script ensuring all packages extract without changes.
This also contains the changes from #3446.

Roll tar to 0.5.5+1

---

test/embedding/embedding_test.dart
test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt

Dart 2.18 will have better stack-traces.
Hardcoded filter of the stacktrace to be compatible with both worlds.

Fix stack-trace expectation

---

lib/src/command.dart
test/golden_file.dart

I think it should be called "exit code" instead "exitcode". Correct me, if I'm wrong.

Fix typo "exitcode"

---

lib/src/global_packages.dart
lib/src/source/git.dart

Fixes https://github.com/dart-lang/pub/issues/3520
Fixes https://github.com/dart-lang/pub/issues/3497
There were remaining uses of `path.prettyUri` on git-URIs. These fails as `Uri.parse` does not handle `git@github.com/a/b.git` style urls. (As discussed in: https://github.com/dart-lang/pub/issues/3377#issuecomment-1091430936)
@mit-mit 
We should consider hotfixing this into 2.18 if there is time.

Fix remaining usages of path.prettyUri on git uris

---

lib/src/dart.dart
pubspec.yaml

Fixes
* https://github.com/dart-lang/pub/issues/3513

Fix null-safety warning in dart.dart

---

doc/repository-spec-v2.md
lib/src/command/lish.dart
lib/src/command/uploader.dart
lib/src/http.dart
lib/src/oauth2.dart
lib/src/pubspec_parse.dart
lib/src/source.dart
lib/src/source/hosted.dart
test/global/activate/custom_hosted_url_test.dart
test/lish/force_does_not_publish_if_there_are_errors_test.dart
test/lish/package_validation_has_an_error_test.dart
test/oauth2/logout_test.dart
test/pubspec_test.dart
test/reformat_ranges_test.dart
test/test_pub.dart
test/testdata/goldens/dependency_services/dependency_services_test/Can update a git package.txt
test/testdata/goldens/dependency_services/dependency_services_test/No pubspec.lock.txt
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/testdata/goldens/embedding/embedding_test/--help.txt
test/testdata/goldens/help_test/pub publish --help.txt
test/token/add_token_test.dart
test/validator/dependency_test.dart
test/validator/pubspec_field_test.dart
test/version_solver_test.dart

Change all mentions of the pub.dartlang.org website to pub.dev in the ui.
Fixes: https://github.com/dart-lang/pub/issues/3519

Use pub.dev in writing

---

lib/src/third_party/tar/README.md
lib/src/third_party/tar/src/reader.dart

This fixes a bug in `package:tar` that occurred when listening to the contents of a tar entry and then cancelling that subscription (https://github.com/simolus3/tar/issues/23). I don't think this affected pub, but Jonas mentioned it'd be good to not let the vendored version diverge.
As usual, I have provided a comparison script in the `compare-tars` branch [of my pub fork](https://github.com/simolus3/pub/tree/compare-tars). The `tool/extract_all_pub_dev.dart` script can be used to compare the two versions.

Upgrade `package:tar` to 0.5.6

---

lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/lock_file.dart
lib/src/null_safety_analysis.dart
lib/src/pubspec.dart
lib/src/solver/package_lister.dart
lib/src/solver/result.dart
lib/src/validator.dart
lib/src/validator/flutter_plugin_format.dart
test/dart3_sdk_constraint_hack_test.dart
test/pubspec_test.dart
test/upgrade/upgrade_null_safety_test.dart
test/version_solver_test.dart

Fixes https://github.com/dart-lang/pub/issues/3554

Make >=2.12 <3.0.0 compatible with dart 3

---

lib/src/global_packages.dart

After realizing that batch-files pick up changes while they are running: https://stackoverflow.com/questions/906586/changing-a-batch-file-when-its-running it seems that it is prudent to avoid changing the offsets inside the file when it is regenerated.
This pr changes two things:
* Always generate the full logic in the binstub (it will check for snapshot presence anyways)
* For windows we generate some padding after the snapshot path, such that changing the path will not affect indices.
This hopefully fixes: https://github.com/dart-lang/pub/issues/3575

Make binstubs offset invariant

---

lib/src/command/lish.dart
lib/src/source/hosted.dart
test/testdata/goldens/hosted/fail_gracefully_on_bad_version_listing_response_test/401-with-message.txt
test/testdata/goldens/hosted/fail_gracefully_on_bad_version_listing_response_test/401.txt
test/testdata/goldens/hosted/fail_gracefully_on_bad_version_listing_response_test/403-with-message.txt
test/testdata/goldens/hosted/fail_gracefully_on_bad_version_listing_response_test/403.txt

- update docs for running 'pub token'
I noticed that the error messages here are outdated - they specified running `pub token` instead of `dart pub token`.

update docs for running 'pub token'

---

lib/src/command/lish.dart
lib/src/command/uploader.dart
lib/src/oauth2.dart
lib/src/source/hosted.dart
test/cache/list_test.dart
test/oauth2/utils.dart
test/pubspec_test.dart
test/token/add_token_test.dart

As content-hashes are introduced with https://github.com/dart-lang/pub/pull/3482 all packages in the cache has to be downloaded again (to validate the hash).
We use this chance to clean up move the client entirely to using pub.dev.
pub.dartlang.org will be rewritten internally, so these should continue working:
* `dart pub token add pub.dartlang.org` (will add a pub.dev token)
* `dependencies: {foo: {hosted: pub.dartlang.org}}`
* `publish_to: pub.dartlang.org`
* `dart pub publish --server=pub.dartlang.org`
This pr will incur a disk-space overhead in existing caches where the pub.dartlang.org directory will linger.
But any kind of reusing the old directory will likely be buggy and have poor backwards compatibility and as mentioned redownloads would happen anyway because of content hashing. …

Completely switch from pub.dartlang.org to pub.dev

---

test/lish/archives_and_uploads_a_package_test.dart
test/package_list_files_test.dart

Solution inspired from here: https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html
Allowing local submodules in tests should carry no security risk.

Workaround to allow using local git submodules in tests

---

lib/src/command/cache.dart
lib/src/command/cache_preload.dart
lib/src/source/hosted.dart
test/cache/preload_test.dart
test/package_server.dart
test/test_pub.dart

Will load one or more tar.gz archives of packages as those served by pub.get and add them to the cache.
Will overwrite an existing entry for the same package-version.
No attempt is made to verify this against what is really being served -> this can be done offline.
Writes the sha256 hash of the archive as the content-hash in the cache -> later pub get invocations will verify the cached hash against what is in the cache.
Fixes: https://github.com/dart-lang/pub/issues/3532

New command `dart pub cache preload`

---

lib/src/entrypoint.dart

Fixes #3659
I'm down for us making progress on ^-syntax, but let's do this in a follow up. I think it's important that we roll this into 2.19.

Suggest using 2.12 as lower-bound SDK constraint

---

lib/src/progress.dart
lib/src/utils.dart

Making a change necessary to get seamless stdout animation when running "pub get" from flutter_tools.
- related: https://github.com/flutter/flutter/issues/74700

Add env var flag to override stdout.hasTerminal for output animations

---

lib/src/entrypoint.dart
lib/src/executable.dart

This partially undoes https://github.com/dart-lang/pub/pull/3652 .
We realized that all `pub global activate`d packages would now be broken on sdk-update.
Still the situation with globally activated packages have other issues. But we need a coherent plan to resolve those.

Only check for sdk updates during `resolveExecutable`

---

lib/src/dart.dart
lib/src/entrypoint.dart
lib/src/executable.dart
pubspec.yaml

https://dart-review.googlesource.com/c/sdk/+/264842 introduces passing `--native-assets` to `gen_kernel`.
This PR enables passing native asset mapping files to the various pub commands compiling kernel, so that these arguments can be passed from dartdev.
Depends on:
* https://github.com/dart-lang/webdev/pull/1797

Support `--native-assets` in kernel compilation commands

---

lib/src/source/git.dart
test/get/git/check_out_test.dart
test/test_pub.dart

Fix of https://github.com/flutter/flutter/issues/116107
I slightly refactored how we read a pubspec from a git revision without checking it out. But unfortunately made a mistake in how we join the lines coming from the git process stdout.
Unfortunately all tests we have of git uses a json descriptor that is not sensitive to removal of newlines.

Fix reading pubspecs from git

---

test/get/git/check_out_test.dart

Not sure why I marked this as skipped back in: https://github.com/dart-lang/pub/pull/2522/commits but it looks like a mistake.

Unskip test

---

lib/src/dart.dart

`path.basename` does not remove the extension of the filename, so we ended up doubling the extension.

Avoid .incremental.dill.incremental.dill in temporary file name

---

lib/src/dart.dart

This reverts commit 74473e12bd82514f24568822d2d2b0893236b319.
This was not the right solution - we still have to come up with the right design here.

Revert "Create output folder if it doesn't exist in the precompiler (#3676)"

---

lib/src/progress.dart
lib/src/utils.dart

Reverts dart-lang/pub#3658
This flag was added with the intention of forcing output animations when run by "flutter pub", but I ended up using `inheritStdio` in https://github.com/flutter/flutter/pull/115801 instead.

Revert "Add env var flag to override stdout.hasTerminal for output animations"

---

lib/src/entrypoint.dart
test/get/sdk_constraint_required_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3661

Suggest environment constraint based on language-version of current sdk

---

lib/src/solver/incompatibility.dart
lib/src/solver/incompatibility_cause.dart
test/dart3_sdk_constraint_hack_test.dart

Refine Dart 3 compatibility output
Fixes https://github.com/dart-lang/pub/issues/3697
```
$ pub get
Resolving dependencies...
The current Dart SDK version is 3.0.0-76.0.dev.
Because oldapp requires SDK version >=2.9.0 <3.0.0, version solving failed.
The lower bound of ">=2.9.0 <3.0.0" does not enable null safety.
```
```
$ ~/dev/pub/bin/pub.exe get
Resolving dependencies...
The current Dart SDK version is 3.0.0-76.0.dev.
Because oldapp doesn't support null safety, version solving failed.
The lower bound of ">=2.9.0 <3.0.0" must be 2.12.0 or higher for null safety.
```

Refine Dart 3 no-null output

---

lib/src/pubspec.dart
test/dart3_sdk_constraint_hack_test.dart

Fixes: https://github.com/dart-lang/pub/issues/3738
This should be hot-fixed onto 2.19 if we can make it (otherwise it'll have no effect)

Only rewrite sdk constraints after dart 3

---

lib/src/command/global_activate.dart
lib/src/global_packages.dart
lib/src/source/hosted.dart
test/lock_file_test.dart

Fix of https://github.com/flutter/flutter/issues/119091
This PR ensures that HostedDescription is always created with a validated and normalized url. That was missing when creating a description from a pubspec.lock file - causing pub to consider the locked package coming from an unrelated host, and thus unlocking it.

Normalize pub.dartlang.org to pub.dev when reading lockfile

---

lib/src/command/remove.dart
test/remove/remove_test.dart

The changes made to this code improve the way dependencies are removed from the pubspec.yaml file. The previous version of the code only removed the package from the dependencies or dev_dependencies key, but it didn't check if the key was now empty after the removal. The updated version now also checks if the key is empty after the removal, and if it is empty, it removes the key as well. This ensures that the pubspec.yaml file is kept clean and organized.
Fixes https://github.com/dart-lang/pub/issues/3530

`dart pub remove`: Remove top-level key if empty after operation.

---

lib/src/pubspec.dart
lib/src/validator/sdk_constraint.dart
test/validator/sdk_constraint_test.dart

Fix of https://github.com/dart-lang/pub/issues/3552

Info when publishing <3.0.0 constraint that is interpreted as <4.0.0

---

lib/src/entrypoint.dart

Updated documentation under entrypoint.acquireDependencies
The documentation regarding useLatest and upgradeAll parameters was removed as they weren't being used anymore and documentation regarding the unlock and analytics parameters was added.
Fix #2956

Updated documentation on entrypoint.acquireDependencies

---

lib/src/command/lish.dart
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/testdata/goldens/lish/many_files_test/displays all files.txt

We are now (purposefully) doing a full `dart analyze` before publication - and that potentially takes a long time.
Fixes: https://github.com/dart-lang/pub/issues/2012

Add a spinner while validating before publishing

---

lib/src/command/token_add.dart
test/token/add_token_test.dart

This PR fixes an issue with a use case I have and apparently also some other people (like https://github.com/dart-lang/pub/issues/3286).
It allows the addition of authorization tokens for `localhost` package repositories. It also works with IPv4 and IPv6 addresses.

Allow addition of tokens for insecure localhost repositories

---

test/lish/unicode_file_names_test.dart

Validating that https://github.com/dart-lang/pub/issues/2362 is no longer a problem.

Add test for publishing and consuming files with unicode characters in name

---

.github/workflows/test.yaml

This flag is being deprecated, and it will make tests load much slower. I tried running locally without it and the tests pass now so I think we can drop it.
Note that we will have the `--compiler source` flag which is similar to this, if indeed the bots are failing we can try that.

Drop --use-data-isolate-strategy flag for tests

---

lib/src/command/lish.dart
lib/src/command/upgrade.dart
lib/src/utils.dart

- remove an extra period from a publish message
- use the `pluralize` method in a few places
This fixes the message `'Package has 0 warnings and 1 hint..'` on a pub publish.

remove an extra period from a publish message

---

lib/src/source/hosted.dart

Informal benchmarks locally have shown that a pub-get on pub itself (already resolved - with warm cache) goes from ~2.0 secs to ~ 1.3 secs.
Examining the top 100 packages from https://pub.dev/help/api#package-names-for-name-completion 29 of them are larger than 100k. None of them are larger than 500k.
If we look at the next 400 packages, no more have listings > 100k.
That means the extra space "wasted" is expected to be pretty small.
So I suggest that we increase this limit.
Here are the top 100 packages with their package-listing sizes (sorted by size):
```
firebase_auth.json                243K
cloud_firestore.json              218K
build_runner.json                 201K
firebase_messaging.json           184K
googleapis.json                   164K
firebase_storage.json             155K …
```

Larger size limit for caching package listings

---

lib/src/git.dart

Fixes: #3799 
If someone has configured settings such as ‘autorun’ to automatically run commands in the terminal, the output of 'git version' may exceed one line, which will lead to incorrect judgment of the original code.
Therefore, in this PR, we search for the git version information in each line of the output. If any line matches the standard git version output format, we will consider it as the version information of git.

Fix wrong action when executing git command

---

lib/src/source/hosted.dart
test/content_hash_test.dart
test/lock_file_test.dart

Fix of https://github.com/dart-lang/pub/issues/3816

Handle malformatted content-hashes in cache, version listing or pubspec.lock

---

lib/src/entrypoint.dart
lib/src/executable.dart

We stopped creating this in https://github.com/dart-lang/pub/pull/1796 (5 years ago, dart v. 2.0.0)

Remove support for .pub package-local cache

---

lib/src/package.dart
test/package_list_files_test.dart

Pub has not created such a folder since https://github.com/dart-lang/pub/pull/1960 (2018)

Don't ignore a folder called 'packages' when publishing

---

lib/src/system_cache.dart

We stopped creating this 3 years ago: https://github.com/dart-lang/pub/pull/2297. ~dart 2.8.

Remove support for PUB_CACHE in APPDATA on windows

---

lib/src/exceptions.dart

This should have been removed with https://github.com/dart-lang/pub/commit/5ca86eb6e7be45ade4e44cbb7402d296cdf8b32f#diff-feaf8fcc8863df13f93c4869c5c1fb17438852a29819581aa1eeb12c26603a2fL87 .

Remove obsolete TODO in exceptions.dart

---

lib/pub.dart

We no longer consume this in the sdk: https://dart-review.googlesource.com/c/sdk/+/286927

Remove the exported deprecatedpubCommand

---

lib/src/command/lish.dart
lib/src/command/login.dart
lib/src/command/logout.dart
lib/src/oauth2.dart
test/oauth2/logout_test.dart

We stopped creating this in dart 2.15
https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#pub-4
One might say we should support this longer - but I think Dart 3.0 is a good place to make this change. And also the consequence is only the user would have to log in again.

Remove support for legacy credentials file

---

lib/src/system_cache.dart
test/golden_file.dart
test/help_test.dart
test/test_pub.dart

We don't want to access the system cache before we need it.
That way we can write the `dart pub token --help` text without having $HOME set.

Lazy construction of cache path.

---

lib/src/command/dependency_services.dart
test/testdata/goldens/dependency_services/dependency_services_test/Can update a git package.txt
test/testdata/goldens/dependency_services/dependency_services_test/multibreaking.txt

We got the following issue reported at dependabot-core: https://github.com/dependabot/dependabot-core/issues/6446.
I think the request is reasonable and I believe it's what we do in other ecosystems.
I researched a bit and I fixed it by special casing exact pinning in pub's dependency services.

If pinned to an exact version, keep the pin when bumping

---

lib/pub.dart

Otherwise we cannot handle failure from the embeddings side.

Throw catchable exception from ensurePubspecResolved

---

lib/src/command/cache_add.dart
lib/src/command/dependency_services.dart
lib/src/solver/result.dart
lib/src/source/cached.dart
lib/src/source/hosted.dart
lib/src/system_cache.dart

We already check if the package exists when doing the download, so we can reuse that check, and avoid implementing a separate (buggy) contains-check.

Refactor `cache add` check for existing package.

---

test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/validator/language_version_test.dart

The broken `langugage_version_test` was not written with much forethought (not that surprising it would be broken by 3.1).
The broken `directory_option_test` was actually broken in https://github.com/dart-lang/pub/pull/3695 (but missed) and now started working again.

Fix tests to work in context of 3.1

---

lib/src/validator/analyze.dart
test/validator/analyze_test.dart

We should not have a different standard for publication than `dart analyze`.
Fixes https://github.com/dart-lang/pub/issues/3870

Don't pass --fatal-infos to `dart analyze` in validation

---

lib/src/command/outdated.dart
test/outdated/outdated_test.dart
test/testdata/goldens/outdated/outdated_test/newer versions available.txt
test/testdata/goldens/outdated/outdated_test/overridden dependencies.txt

Also use "strictly less" instead of "different" when counting upgradable/resolvable versions.
Fixes: https://github.com/dart-lang/pub/issues/3874

Use the lockfile when computing upgradable, resolvable in outdated

---

lib/src/command/lish.dart
test/testdata/goldens/help_test/pub publish --help.txt

An escape-hook if we have mistakes in our validations.
Fixes https://github.com/dart-lang/pub/issues/3901

Flag `pub publish --skip-validation` to publish without resolution and validation

---

lib/src/lock_file.dart
test/lock_file_test.dart

Makes sure to throw the right Exception kind.
Also fixes some punctuation funkyness in the error message.
Fixes: https://github.com/dart-lang/pub/issues/3926

Gracefully handle version in lockfile not parsing

---

pubspec.yaml

The 1.0.0 release does not have breaking changes.
Remove the pre-release suffix from the SDK constraint now that the
stable SDK is published. Remove unneeded quotes from SDK constraint.

Expand constraint for `http`

---

test/global/run/package_api_test.dart
test/run/package_api_test.dart

`Isolate.packageRoot` didn't do anything anymore, and with https://github.com/dart-lang/sdk/commit/e24899bac1964b4e21f8032d0c9ac45fabfe41cc it doesn't even exist.

Remove usage of Isolate.packageRoot from tests

---

lib/src/command/add.dart
lib/src/command/upgrade.dart
lib/src/pubspec_utils.dart
test/add/hosted/non_default_pub_server_test.dart
test/upgrade/upgrade_major_versions_test.dart

Fix of: https://github.com/dart-lang/pub/issues/3942
Turns out there even was an old todo to do this :)

Handle non-default hosts in `upgrade --major-versions`

---

lib/src/solver/report.dart
test/get/hosted/warn_about_discontinued_test.dart
test/test_pub.dart
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/testdata/goldens/embedding/embedding_test/--color forces colors.txt
test/testdata/goldens/upgrade/example_warns_about_major_versions_test/pub upgrade --major-versions does not update major versions in example~.txt
test/upgrade/hosted/warn_about_discontinued_test.dart
test/upgrade/report/describes_change_test.dart
test/upgrade/report/leading_character_shows_change_test.dart

* Don't mention unchanged deps in `upgrade` report
* Give summary of changes in `pub get` report
Fixes: https://github.com/dart-lang/pub/issues/2863
Before:
```
> dart pub upgrade
Resolving dependencies... (2.0s)
_fe_analyzer_shared 61.0.0
analyzer 5.13.0
args 2.4.2
async 2.11.0
> boolean_selector 2.1.1 (was 2.1.0)
checked_yaml 2.0.3
cli_util 0.4.0
collection 1.17.2
convert 3.1.1
coverage 1.6.3
crypto 3.0.3
file 7.0.0
frontend_server_client 3.2.0
glob 2.1.2
http 1.0.0
http_multi_server 3.2.1
http_parser 4.0.2
io 1.0.4
js 0.6.7
json_annotation 4.8.1
lints 2.1.1
logging 1.2.0
matcher 0.12.16
meta 1.9.1
mime 1.0.4
node_preamble 2.0.2
package_config 2.1.0
path 1.8.3
pool 1.5.1
pub_semver 2.1.4
pubspec_parse 1.2.3
retry 3.1.2
shelf 1.4.1
shelf_packages_handler 3.0.2
shelf_static 1.1.2 …
```

Adjust report

---

lib/src/command/add.dart

Fixes: https://github.com/dart-lang/pub/issues/3860
(this only affects the legacy syntax).

`pub add` Rely on git sources validation of --git-url

---

lib/src/entrypoint.dart
lib/src/package.dart
lib/src/pubspec.dart
lib/src/solver/result.dart
lib/src/source/cached.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
lib/src/source/path.dart
lib/src/source/sdk.dart
lib/src/system_cache.dart
test/ascii_tree_test.dart
test/directory_option_test.dart
test/get/git/dependency_name_match_pubspec_test.dart
test/pubspec_test.dart
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/upgrade/git/upgrade_to_incompatible_pubspec_test.dart

Also report the error from the referencing pubspec.
Fixes https://github.com/dart-lang/pub/issues/2096

Validate pubspec names after resolution, instead of when parsing

---

analysis_options.yaml
lib/src/ascii_tree.dart
lib/src/command/dependency_services.dart
lib/src/dart.dart
lib/src/exceptions.dart
lib/src/git.dart
lib/src/http.dart
lib/src/ignore.dart
lib/src/io.dart
lib/src/isolate.dart
lib/src/log.dart
lib/src/solver/assignment.dart
lib/src/solver/set_relation.dart
lib/src/solver/type.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
lib/src/source/path.dart
lib/src/source/root.dart
lib/src/source/sdk.dart
lib/src/source/unknown.dart
lib/src/utils.dart
test/descriptor.dart
test/descriptor/git.dart
test/descriptor/tar.dart
test/descriptor/yaml.dart
test/test_pub.dart
tool/extract_all_pub_dev.dart
tool/test-bin/pub_command_runner.dart
tool/test.dart

Simplifies code while bringing the repository closer to being able to switch to [`package:dart_flutter_team_lints`](https://github.com/dart-lang/ecosystem/tree/main/pkgs/dart_flutter_team_lints) for analysis.

Enable lints to use new language features

---

lib/src/dart.dart

https://github.com/dart-lang/pub/issues/3978
Not a real fix, but should make it slightly easier to follow what goes on if this happens again.

Log missing compilation output

---

test/version_solver_test.dart

The output changed after dart 3.2 came out.
Perhaps we should also fake the flutter version listings during testing...

Fix test expectation

---

pubspec.yaml

I didn't see a reason for this to be a normal dependency.

Switch vendor to a dev dependency

---

lib/src/command/upgrade.dart
test/testdata/goldens/help_test/pub upgrade --help.txt
test/upgrade/upgrade_tighten_test.dart

Used to programmatically tighten lower bounds on dependencies in pubspec.yaml
For a Dart project pubspec.yaml gives the version constraints of a project's dependencies. And pubspec.lock contains the current resolution of concrete versions to fulfill those constraints.
Currently the command dart pub upgrade can help the user upgrade the version of a dependency that a user is locked on in pubspec.lock within the current constraint from pubspec.yaml.
dart pub upgrade --major-versions can help upgrade the constraint to bump the constraint to a later version range. It will also upgrade the lower bound, but only of those packages that needed a breaking change.
When you are authoring a package for others to consume, it makes sense to have as wide constraints as possible to minimize version …

`upgrade --tighten`

---

doc/cache_layout.md
doc/dart_tool_layout.md
lib/src/dart.dart
lib/src/entrypoint.dart
pubspec.yaml
test/precompilation_test.dart
tool/test.dart

This ensures that the "incremental" file that is created when precompilation fails, will be removed when precompilation succeeds.
Fixes: https://github.com/dart-lang/pub/issues/4003
Also simplifies the path of the incremental file to be `$output.incremental`. This simplifies the directory handling a bit.
Fixes: https://github.com/dart-lang/pub/issues/3896
Added a test that caching takes effect (such that second compilation is much faster). This test is somewhat fragile - but I'm not sure we have a better way to test this.

Improve precompilation

---

analysis_options.yaml
lib/src/command.dart
lib/src/command/dependency_services.dart
lib/src/error_group.dart
lib/src/lock_file.dart
lib/src/oauth2.dart
lib/src/source/hosted.dart
lib/src/utils.dart
test/cache/list_test.dart
test/dependency_services/dependency_services_test.dart
test/embedding/ensure_pubspec_resolved.dart
test/error_group_test.dart
test/lish/cloud_storage_upload_doesnt_redirect_test.dart
test/lish/cloud_storage_upload_provides_an_error_test.dart
test/lish/utils.dart
test/oauth2/with_a_server_rejected_refresh_token_authenticates_again_test.dart
test/test_pub.dart
test/token/remove_token_test.dart
test/token/when_receives_401_removes_token_test.dart
test/utils_test.dart
tool/extract_all_pub_dev.dart

Enabling this analyzer language mode to get closer to switching to `dart_flutter_team_lints` which enables it by default.

Enable 'strict-inference' language analysis mode

---

lib/src/validator/leak_detection.dart
test/validator/leak_detection_test.dart

Timing each `LeakPattern` and the creation of `SourceFile` separately in a repo with a single 150MB file of random bytes revealed this:
```
AWS Access Key: 190 ms
AWS Secret Key: 1434 ms
Google API Key: 143 ms
Google OAuth ID: 337 ms
Google OAuth Refresh Token: 244 ms
Google OAuth Access Token: 97 ms
Private Key: 169 ms
RSA Private Key: 156 ms
EC Private Key: 179 ms
PGP Private Key: 227 ms
creating source files: 45777 ms
```
With this change, leak detection for big files will look like:
````
Publishing _dummy_pkg 0.0.1-toobig to https://pub.dev:
├── CHANGELOG.md (<1 KB)
├── LICENSE (<1 KB)
├── README.md (<1 KB)
├── pubspec.yaml (<1 KB)
└── testfile (146 MB)
Validating package... (14.3s)
Package validation found the following errors:
* Potential leak of Private Key in testfile at offset …
```

Only create SourceFile for leak on demand

---

lib/src/pub_embeddable_command.dart
lib/src/solver/result.dart
pubspec.yaml
test/embedding/embedding_test.dart
tool/test-bin/pub_command_runner.dart

This is some prerequisite work for migrating package:dartdev to use package:unified_analytics.
I've removed the single analytics test here in favour of the dart pub get analytics test in dartdev for simplicity, as package:unified_analytics adds a FakeAnalytics class that tracks analytics events for easy validation in tests without needing to manually serialize all the analytics events. It's not possible to serialize / deserialize FakeAnalytics so the results can't be verified from a separate process at this point, so this testing is easier to do in dartdev. If you'd prefer we keep this testing here, please let me know if you have ideas on how to move forward 😊

Migrate pub to use package:unified_analytics

---

lib/src/validator/relative_version_numbering.dart
test/validator/relative_version_numbering_test.dart

Fixes: https://github.com/dart-lang/pub/issues/4051
When there was no prerelease component, we would produce an empty-string prerelease component instead of null.

Fix calculation version number without build part

---

lib/src/validator/analyze.dart
test/validator/analyze_test.dart

`build.dart` (and later `link.dart`) are used by dependencies, so they are part of the set of files of a package which dependencies use (besides just `lib/` and `bin/`).
For more info about `build.dart` and `link.dart` see https://github.com/dart-lang/native.
Follow up of: https://github.com/dart-lang/pub/pull/4068
---
<details>
- Most changes should add an entry to the changelog and may need to …

Analyze `build.dart` and `link.dart`

---

lib/src/entrypoint.dart
lib/src/solver/report.dart

Should make it more obvious that `--enforce-lockfile` does the right thing.
(Notable there was a discrepancy such that in some cases changing a dependency to a dev-dependency would count as a change, and sometimes not. Now it is not considered a change.)
Fixes: https://github.com/dart-lang/pub/issues/4075

Refactor change-detection for --enforce-lockfile

---

lib/src/http.dart

Fix of https://github.com/dart-lang/pub/issues/4094
Keeps track of whether we have closed the global http-client (indicating processing is done, and we are ready to exit the program, and avoid doing retries at that point), in that case avoid doing restarts.
Would be more elegant to have this as a method on the client itself - avoiding a reference to the global client, but many times we wrap the global client in an Oauth2 client.
Would be more elegant if we could distinguish the ClientException we get when a request times out, from the one we get when the client is closed. (And not rely on parsing the message string).
Hard to write a good test for, but manual testing has shown that the hanging problem goes away with this fix.
When doing http requests with retries we retry on all …

Avoid retrying queries after closing client

---

lib/src/validator.dart
test/validator/strict_dependencies_test.dart

Fix of https://github.com/dart-lang/pub/issues/4115
We checked if the normalized path (without the final path seperator) was a prefix of the file path
Therefore we were told that `bindings_generator/abc.dart` is inside `bin/`.

Fix path-matching expression

---

lib/src/entrypoint.dart
test/embedding/ensure_pubspec_resolved.dart

We revalidate the contents of pubspec.lock and package_config when either:
* "Modified" timestamps are out of order (eg. pubspec.yaml is newer than pubspec.lock)
* We have path-dependencies
In both of these cases we currently touch the files if the contents is valid, to make the "modified" timestamps in the right order. This is unnecessary in the second case - because they are already ordered correctly, and it trips up other processes relying on the "modified" timestamps or listens for changes.
Fixes https://github.com/dart-lang/pub/issues/3016

Don't touch package_config.json when not needed

---

lib/src/command/upgrade.dart
lib/src/solver/failure.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
lib/src/system_cache.dart

* Replace `.whereNotNull()` with `.nonNulls` which is now in Dart core.
* `.firstOrNull`, `.lastOrNull`, `.singleOrNull` and `.elementAtOrNull(i)` are also in Dart core and even under the same name, so simply drop the import of 'package:collection' whenever possible.
Not updating the changelog because there's 0 visible change to users.
---
<details>
- Most changes should add an entry to the …

Remove unnecessary imports of 'package:collection' `IterableExtension`

---

lib/src/language_version.dart
lib/src/pubspec.dart
lib/src/utils.dart
lib/src/validator/pubspec_typo.dart
test/pubspec_test.dart

Part of https://github.com/dart-lang/pub/issues/4127
Just the pubspec syntax support.
The feature is only enabled from language version 3.7 (far in the future) in that way we should not break any users
The exact language version should be adjusted when we are ready.

Support for workspace syntax in pubspec.yaml

---

lib/src/command/dependency_services.dart
lib/src/source/git.dart
test/get/git/ssh_url_test.dart

Aligns with the other `ResolvedDescription` types.

Rename GitResolvedDescription to ResolvedGitDescription

---

lib/src/command/add.dart
lib/src/command/dependency_services.dart
lib/src/command/outdated.dart
lib/src/command/upgrade.dart
lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/package.dart
lib/src/package_name.dart
lib/src/solver/package_lister.dart
lib/src/solver/solve_suggestions.dart
lib/src/source/root.dart

This is refactor that is extracted from https://github.com/dart-lang/pub/pull/4060 . It will allow a RootDescription to be created before the pubspec is loaded.
This removes the concept of an "in-memory package". These packages were always a modified version of a pubspec, being used for trying out a resolution, and they might as well be associated with the directory of the original pubspec.

Make a RootDescription not depend on the root Package

---

lib/src/http.dart
test/package_server.dart

This should resolve some flakynes observed in tests.
Because binding to port 0 `localhost` will bind to a random free port on one of `127.0.0.1` (ipv4) and `::1` (ipv6) it risks colliding with a different service with the same port, but the other ipvx.
When pub then connects to `localhost` it will race ipv4 against ipv6, causing flakiness.
Note that pub always will canonicalize loopbacks 127.0.0.1 and ::1 to `localhost` for cache directory names and for lockfile purposes.

Prefer IPV4 on localhost, serve testserver on IPV4

---

lib/pub.dart
lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/io.dart
test/add/sdk/sdk_test.dart
test/descriptor.dart
test/descriptor/package_config.dart
test/embedding/ensure_pubspec_resolved.dart
test/sdk_test.dart
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt

Updates the logic we use in `_isUptoDate`.
Fixes https://github.com/dart-lang/pub/issues/4153
Instead of grepping the lockfile for presence of path-dependencies we compare timestamps against the `pubspec.yaml`s of all packages mentioned in `.dart_tool/package_config.json`. In the "fast" case we avoid reading any other file than `package_config.json`, and avoid dealing with yaml.
This will make `_isUpToDate` possible when we introduce workspace support. We don't need to parse pubspec.yamls to find all packages in the workspace, but can rather just look at all the entries in `package_config.json`.
This PR also adds new entries in package_config.json: pub_cache, flutter_root and flutter_version. If any of these changes, we require a new resolution.
We remove the "checkForSdkUpdate" option. …

isUpToDate based on package_config.json

---

lib/src/global_packages.dart

Fixes https://github.com/dart-lang/pub/issues/4162
We could also point to some online guide for adding stuff to path. Possibly via a dart.dev/go - link...
Or find the default shell by looking at $SHELL
WDYT?

Mention .zshrc as possible shell config file

---

test/get/hosted/advisory_test.dart
test/outdated/outdated_test.dart
test/package_server.dart

This enables testing security advisories with affected package fields that have other ecosystems specified.

Refactor test setup for security advisories

---

lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/global_packages.dart
test/global/run/fails_if_sdk_constraint_is_unmet_test.dart

Until now `Entrypoint`s of cached global packages had a separate `rootDir` (folder in `<PUB_CACHE>/hosted/<package>`) and `globalDir` (folder in `<PUB_CACHE>/global_packages/<package>`.
Instead with this PR we treat it more like a regular package with a `rootDir` at `<PUB_CACHE>/global_packages/<package>` that has the activated package as a single dependency.
The package layout inside the package folder is still a bit different (using `bin/<snapshot>` instead of `.dart_tool/pub/bin/package/<snapshot>` to store snapshots) so we still maintain a `isCachedGlobal` state.
Globally activated packages from path are different. The `<PUB_CACHE>/global_packages/<package>` folder contains a "fake" pubspec.lock that points to the real package. And that package is used as root for the global …

Remove Entrypoint._configRoot

---

tool/test.dart

Makes running a single test a few seconds faster (after first run)

Use resident compiler to start test runner

---

lib/src/entrypoint.dart
lib/src/executable.dart

Change snapshot deletion to only delete snapshots made by different sdk's.
This is such that the `.dart_tool` folder will not grow without bounds.
This requires that we rebuild even snapshots from mutable packages after pub get. So this pr also adds a timestamp check comparing the snapshot modified time to the `.dart_tool/package_config.json` modified time. And will recompile if the snapshot is older, even for immutable packages.
This is not as bad as it sounds, because we are doing incremental recompilation.
Fixes https://github.com/dart-lang/pub/issues/4161
`pub get` and `dart run` will still race if they are run concurrently from **different** sdks. But that seems acceptable.

More robust snapshot deletion

---

lib/src/command/lish.dart

No reason to run all validations if you should not publish at all.
I believe this will also fix https://github.com/dart-lang/pub/issues/4177
We allow `--dry-run` such that people can still use it in CI.

Test for pubspec privateness before running validations

---

test/lish/uses_publish_to_url_test.dart

Seems like requesting from example.com is flaky in the CI. So set up a fake server and use that for validations.
Should fix https://github.com/dart-lang/pub/issues/4177

Use existing server for test

---

test/descriptor.dart
test/workspace_test.dart

The existing test 'reports errors in workspace pubspec.yamls correctly' was actually testing that 'ignores the source of dependencies on root packages. (Uses the local version instead)'. Fixed
Contains tests for
* Syntax errors  in workspace pubspecs.
* Solve errors in dependencies of a workspace pubspec
* Rejecting a pubspec without "resolution: workspace" in a workspace.

Tests of workspace error handling

---

lib/src/entrypoint.dart
test/workspace_test.dart

Remove stray lockfiles and packageconfigs from workspace

---

lib/pub.dart

https://github.com/dart-lang/sdk/issues/55289

Close the global http client after `ensurePubspecResolved`

---

lib/src/global_packages.dart
test/global/binstubs/binstub_runs_global_run_if_no_snapshot_test.dart

By mistake we were using the name of the dummy-package "pub global activate" instead of the activated package.

Fix package name when refreshing binstubs

---

lib/src/package.dart
test/workspace_test.dart

Related to https://github.com/dart-lang/pub/issues/4127

Show parent pubspecs when a pubspec could not be found.

---

lib/src/command/add.dart
lib/src/command/dependency_services.dart
lib/src/command/remove.dart
lib/src/command/upgrade.dart
lib/src/entrypoint.dart
lib/src/package.dart
lib/src/pubspec.dart
lib/src/pubspec_utils.dart
test/workspace_test.dart

Handle whole workspace in `pub upgrade [--tighten|--major-versions]`

---

lib/src/entrypoint.dart
lib/src/package.dart
test/workspace_test.dart

Can happen eg. when:
* root includes `a` and  `a/b`
* `a` includes `b`
An alternative would be to allow this and canonicalize, but I'm not sure about the implications, so my intuition is to restrict here.

Report failure if package is included twice in same workspace

---

lib/src/solver/package_lister.dart
test/workspace_test.dart

By making a constraint on the exact package version of the workspace child we avoid the solver telling us that "every versions of" the package does something.
Relates to #4127

Make solve traces more precise for workspace members

---

lib/src/http.dart
test/lish/archives_and_uploads_a_package_test.dart
test/lish/force_publishes_if_tests_are_no_warnings_or_errors_test.dart
test/lish/force_publishes_if_there_are_warnings_test.dart
test/lish/many_files_test.dart
test/lish/package_creation_provides_an_error_test.dart
test/lish/package_validation_has_a_warning_and_continues_test.dart
test/lish/publishing_to_and_from_archive_test.dart
test/lish/unicode_file_names_test.dart
test/lish/upload_form_provides_an_error_test.dart
test/testdata/goldens/lish/many_files_test/displays all files.txt

Making it harder for a rouge server to impersonate the pub client, and/or to mess up the terminal with bad characters.

Sanitize publication responses from server

---

lib/src/entrypoint.dart
lib/src/package.dart
lib/src/package_config.dart
test/workspace_test.dart

Part of #4127 
This will otherwise lead to broken behavior with malformed package_configs.
https://github.com/dart-lang/pub/pull/4232

Detect duplicate names in workspace packages

---

lib/src/entrypoint.dart
lib/src/package.dart
test/workspace_test.dart

Don't print 'Resolving dependencies in `../..`...' Use absolute path instead

---

lib/src/entrypoint.dart
test/workspace_test.dart

This file can be used for the fast path of `ensureUpToDate` to find the root pubspec.yaml without parsing the intermediate pubspec.yaml files.
Part of https://github.com/dart-lang/pub/issues/4239
Related to https://github.com/dart-lang/sdk/issues/55548

Write .dart_tool/pub/workspace_ref.json

---

lib/src/global_packages.dart
test/global/binstubs/binstub_runs_global_run_if_no_snapshot_test.dart

This reverts commit ed20b45589766d6fd135e93460b9e8255ccba519 (#4205) because it is causing the Flutter build to fail with concurrency issues. See https://github.com/flutter/flutter/issues/147609
@sigurdm 
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-cha …

Revert "Fix package name when refreshing binstubs (#4205)"

---

lib/src/global_packages.dart
test/global/binstubs/binstub_runs_global_run_if_no_snapshot_test.dart

Reapply "Fix package name when refreshing binstubs (#4205)" (#4255)
Fix the underlying problem, where `p.join(tempdir, binstubPath)` evaluates to `binstubPath` because it is absolute. Therefore we did not chmod the binstub in a tempdir before moving it 🤦 .
Also avoids deleting a binstub before refreshing it, so an outside observer will never see a missing binstub. Only either before or after.
Should fix https://github.com/flutter/flutter/issues/147609

Reapply binstub fix

---

lib/src/command/unpack.dart
test/testdata/goldens/help_test/pub unpack --help.txt
test/unpack_test.dart

Also renames "constraint" to "descriptor" to be consistent with the terminology from `dart pub add`.

Clean up copy and formatting of unpack command help

---

lib/src/entrypoint.dart

I don't really think these help us.
They were added in https://github.com/dart-lang/pub/pull/4171/files#diff-fdb8ce649c4af89ef6afd8c67bdd9e51e661161792256adba203cbd241f64ad2R706

Remove debug logging statements

---

lib/src/entrypoint.dart
lib/src/executable.dart
lib/src/io.dart
test/descriptor.dart
test/embedding/ensure_pubspec_resolved.dart
test/embedding/get_executable_for_command_test.dart

Fixes https://github.com/dart-lang/pub/issues/4239
Consumes the workspace_ref files added in https://github.com/dart-lang/pub/pull/4240 to quickly locate the workspace root.

Allow invoking `getExecutableForCommand` everywhere in workspace

---

lib/src/source/hosted.dart
test/dependency_services/dependency_services_test.dart
test/testdata/goldens/dependency_services/dependency_services_test/Preserves pub.dartlang.org as hosted url.txt

Fixes the test that would otherwise connect to pub.dev when finding the latest.
This broke the golden file, when somebody actually published a package:bar.

Connect to _PUB_TEST_DEFAULT_HOSTED_URL instead of pub.dev when testing

---

lib/src/entrypoint.dart
test/embedding/get_executable_for_command.dart
test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt

When run in a subdirectory of the workspace-root, `ensureUpToDate` would fail to find the pubspec.yamls of dependencies because it would search for them relative to CWD, not to the root directory, and thus conclude the package needs a new resolution.

Fix fast path check of ensureUpToDate

---

lib/src/entrypoint.dart
test/embedding/ensure_pubspec_resolved.dart

Double bug!
The branches of the conditional were swapped, **and** the comparison was between a `String` and a `Version`.

Fix flutter version update on fast path

---

lib/src/entrypoint.dart
test/embedding/ensure_pubspec_resolved.dart
test/embedding/get_executable_for_command.dart

We for some bogus reason added the text of the file in the path...
It happened to work by accident in the existing test cases.

Fix bug in ensureUpToDate fast path, when following workspaceRef

---

lib/src/command/outdated.dart
test/testdata/goldens/help_test/pub outdated --help.txt
test/testdata/goldens/outdated/outdated_test/do not report ignored advisories.txt
test/testdata/goldens/outdated/outdated_test/do not show advisories if no version is affected.txt
test/testdata/goldens/outdated/outdated_test/does not allow arguments - handles bad flags.txt
test/testdata/goldens/outdated/outdated_test/newer versions available.txt
test/testdata/goldens/outdated/outdated_test/only report unignored advisory.txt
test/testdata/goldens/outdated/outdated_test/show advisory - all versions.txt
test/testdata/goldens/outdated/outdated_test/show advisory - current also retracted.txt
test/testdata/goldens/outdated/outdated_test/show advisory - current, same package mentioned twice.txt
test/testdata/goldens/outdated/outdated_test/show advisory - current.txt
test/testdata/goldens/outdated/outdated_test/show advisory - latest also discontinued.txt
test/testdata/goldens/outdated/outdated_test/show advisory - latest.txt
test/testdata/goldens/outdated/outdated_test/show advisory - several advisories.txt
test/testdata/goldens/outdated/outdated_test/show discontinued and retracted.txt
test/testdata/goldens/outdated/outdated_test/show discontinued with no latest version.txt
test/testdata/goldens/outdated/outdated_test/show discontinued.txt
test/testdata/goldens/outdated/outdated_test/show retracted.txt

https://github.com/dart-lang/pub/issues/4273

`outdated` show transitive dependencies by default

---

test/workspace_test.dart

Test publishing from workspace

---

test/workspace_test.dart

Test that consuming packages out of their workspace context works

---

lib/src/io.dart

Reading the linux man page for [`rename(2)`](https://man7.org/linux/man-pages/man2/rename.2.html) again, it is clear that the file system can respond with **either** error-code EEXISTS or ENOTEMPTY when the destination directory exists and is not empty. We were only catching one of these.
Fixes https://github.com/dart-lang/pub/issues/4285
I'm not so sure about macOS. There is also an EEXIST. Man page says:
```
[EEXIST]           flags has RENAME_EXCL set but new already exists.
```
I [think](https://github.com/dart-lang/sdk/blob/b68351fbc3b227ee87244d394c0e7d6bf4d06e25/runtime/bin/directory_macos.cc#L444) that dart:io on mac is not setting any flags in its rename call, but I'm assuming there is very little harm.

Handle file system error 17 (EEXIST) on linux and macos

---

lib/src/entrypoint.dart
test/workspace_test.dart

Follow-up to https://github.com/dart-lang/pub/pull/4231
```
/usr/local/google/home/sigurdm/projects/pub-dev/app > dart pub get
Resolving dependencies in `/usr/local/google/home/sigurdm/projects/pub-dev`...  # <--- already fixed here
Downloading packages... 
archive 3.5.1 (3.6.0 available)
[...]
web_socket_channel 2.4.5 (3.0.0 available)
Got dependencies in `..`! # <------ now fixing this.
14 packages have newer versions incompatible wit
```

Also use absolute path in solve report, when root is a parent

---

lib/src/validator/sdk_constraint.dart

The caret syntax is allowed since #3672

Remove a stale statement in a doc comment

---

lib/src/source/path.dart
test/get/git/check_out_transitive_test.dart

Fixes https://github.com/dart-lang/pub/issues/4314

Use forward slashes in paths when using path dependencies from git dependencies

---

analysis_options.yaml

The upgrade of some warnings to errors was intended to make external CI
a closer match to google3. Since then we have started using
`--fatal-infos` which makes it unnecessary to make these errors.
The TODO ignore is unnecessary because the analysis server no longer
includes TODO comments in the list of diagnostics.

Remove some unnecessary analysis options

---

analysis_options.yaml

I prefer todos to not show up in my problems view in vscode.
This is the best solution I've found for this.
Reverts a change made in https://github.com/dart-lang/pub/pull/4331

Ignore todos

---

lib/src/authentication/credential.dart
lib/src/authentication/token_store.dart

And only let 'token remove' resave it when actually mutated.
Also includes a few comment fixes.

Avoid reloading credentials file on each getter access

---

lib/src/source/cached.dart
lib/src/system_cache.dart
test/package_config_file_test.dart

This was the case until https://github.com/dart-lang/pub/pull/4171 . I believe that was a regression.

Use relative path in package_config.json when PUB_CACHE is relative

---

lib/src/git.dart
lib/src/validator.dart
lib/src/validator/git_status.dart
lib/src/validator/gitignore.dart
test/git_test.dart
test/validator/git_status_test.dart

Fixes https://github.com/dart-lang/pub/issues/2040
Does not warn about newly added files, because they might get generated by a build step.

Validate git is clean when publishing

---

lib/src/package_graph.dart
test/embedding/embedding_test.dart

Fixes https://github.com/dart-lang/pub/issues/4390

Consider sdk packages immutable

---

lib/src/command/deps.dart
pubspec.lock
test/deps_test.dart
test/testdata/goldens/deps/executables_test/applies formatting before printing executables.txt
test/testdata/goldens/deps/executables_test/dev dependencies.txt
test/testdata/goldens/deps/executables_test/lists Dart executables, without entrypoints.txt
test/testdata/goldens/deps/executables_test/lists executables from a dependency.txt
test/testdata/goldens/deps/executables_test/lists executables only from immediate dependencies.txt
test/testdata/goldens/deps/executables_test/overriden dependencies executables.txt
test/testdata/goldens/deps/executables_test/skips executables in sub directories.txt
test/testdata/goldens/deps/executables_test/skips non-Dart executables.txt
test/workspace_test.dart

Split out directDependencies and devDependencies in `pub deps`

---

lib/src/command/add.dart
test/add/common/add_test.dart

Fix an issue that prevented users from adding cached packages using the --offline flag through the **add** command line when the system is offline.
Steps:
Run the following command in an offline state (no internet connection):
`dart pub add package_name --offline`

Fix add package with offline flag

---

lib/src/command/upgrade.dart
lib/src/entrypoint.dart
pubspec.yaml
test/testdata/goldens/help_test/pub upgrade --help.txt
test/upgrade/upgrade_transitive_test.dart

`pub upgrade x y z` will only unlock x, y and z, but with the new flag `pub upgrade --transitive x y z` will unlock those packages **and** their transitive dependencies.
Same for `--major-versions`.
Fixes https://github.com/dart-lang/pub/issues/3504
We could also consider making this the default behavior - it is most likely what people expect.

Add flag `--unlock-transitive` to `pub upgrade`

---

lib/src/command/upgrade.dart
pubspec.lock
test/testdata/goldens/help_test/pub upgrade --help.txt
test/upgrade/upgrade_transitive_test.dart

Follow-up to: https://github.com/dart-lang/pub/pull/4403
Fix failing tests
Make the flag non-negatable.

Follow up to `--unlock-transitive`

---

lib/src/global_packages.dart
test/global/run/recompiles_if_snapshot_is_out_of_date_test.dart

Also show the SolveReport, to clarify what in the resolution has changed

Special case global-run message for updated sdk

---

lib/src/command/get.dart
pubspec.lock
test/testdata/goldens/help_test/pub get --help.txt

Fixes https://github.com/dart-lang/pub/issues/4093

Better help message for --enforce-lock-file

---

lib/src/entrypoint.dart
lib/src/package.dart
pubspec.lock
test/workspace_test.dart

Fixes https://github.com/dart-lang/pub/issues/4445
Also makes resolution error if there are any pubspec.yaml's in such directories.

Delete directories between workspace package and workspace root

---

lib/src/global_packages.dart
lib/src/language_version.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
test/pubspec_test.dart
test/unknown_properties_in_description_test.dart

Fixes #4444 
We don't special case root packages. In a few versions the difference will be moot anyway

Forbid unknown description keys (after 3.7)

---

lib/src/package.dart
pubspec.lock
test/workspace_test.dart

Fixes https://github.com/dart-lang/pub/issues/4468

Don't iterate above the root dir when finding stray pubspecs

---

lib/src/command/add.dart
test/testdata/goldens/help_test/pub add --help.txt

Update `add` helping messages

---

lib/src/source/path.dart

The `canonicalize` function is very slow, and the solver compares these a number of times.
This attempt of migrating the sdk to use workspaces https://dart-review.googlesource.com/c/sdk/+/397164?tab=comments has all third-party dependencies overridden as path-dependencies. 71 dependencies.
With current pub, this takes 2.245s to resolve on my machine.
After this fix it takes: 0.117s to resolve!
Also this avoid potential issues of inconsistencies if files change during resolution (although, still don't do that).

Cache canonicalized version of paths in path dependencies

---

lib/src/global_packages.dart
test/global/activate/activate_casing_test.dart
test/global/activate/fails_when_active_package_is_corrupt_test.dart

Also handle a global lockfile without the right package name gracefully.
Fixes #4513

Disallow activating packages with non-lowercase letters

---

lib/src/entrypoint.dart
lib/src/package_config.dart
test/descriptor/package_config.dart
test/package_config_file_test.dart
test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt

Based on textual equality
Also removes the timestamp from package_config.json
Fixes https://github.com/dart-lang/sdk/issues/60371

Don't rewrite package_config and package_graph if unchanged

---

lib/src/command/add.dart
lib/src/command/dependency_services.dart
lib/src/command/lish.dart
lib/src/command/unpack.dart
lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/pubspec.dart
lib/src/source.dart
lib/src/source/cached.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
lib/src/source/path.dart
lib/src/source/root.dart
lib/src/source/sdk.dart
lib/src/source/unknown.dart
test/pubspec_test.dart
test/version_solver_test.dart

When we are reading the pubspec of a package we already know exactly where we found the package (the resolved description).
This will make a difference when we want to resolve path dependencies relative to a git dependency, where you need to know exactly what revision to look in.
Extracted from https://github.com/dart-lang/pub/pull/4427

Resolve pubspec dependencies relative to the Resolved description of their containing package

---

lib/src/command/add.dart
lib/src/command/upgrade.dart
lib/src/package_name.dart
lib/src/solver/version_solver.dart
lib/src/source.dart
lib/src/source/git.dart
lib/src/source/hosted.dart
lib/src/source/path.dart
lib/src/source/root.dart
lib/src/source/sdk.dart
lib/src/source/unknown.dart

Extracted from #4427 . With that PR a git dependency can have multiple versions. But only if it is a "tag_pattern".

Move hasMultipleVersions to Description

---

lib/src/entrypoint.dart
lib/src/io.dart
lib/src/lock_file.dart
test/package_config_file_test.dart

We did this for package_config. No reason not to do the same for the other files, rather it causes trouble not to.
Fixes #4588

Don't rewrite pubspec.lock and workspace_ref if not modified

---

doc/cache_layout.md
lib/src/entrypoint.dart
lib/src/global_packages.dart
lib/src/io.dart
lib/src/system_cache.dart
test/cache/gc_test.dart
test/embedding/embedding_test.dart
test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt

This is preparing for a `dart pub cache gc` command for clearing up the cache.
By storing inside the cache where each "activated" package is, we enable "gc'ing" by finding all cached packages not referenced by an active package.

Mark package-configs as active when writing

---

lib/src/language_version.dart
lib/src/lock_file.dart
lib/src/pubspec.dart
test/get/flutter_constraint_upper_bound_ignored_test.dart
test/pubspec_test.dart

Solves https://github.com/flutter/flutter/issues/95472 (at least partially)
By making this depend on language version we avoid a breaking change

Respect upper bound of Flutter constraint in root packages after 3.9

---

lib/pub.dart
lib/src/pub_embeddable_command.dart

We'd like to add categories to the commands in `dartdev`:
```
$ dart --help
A command-line utility for Dart development.
Usage: dart <command|dart-file> [arguments]
Global options:
-v, --verbose               Show additional command output.
--version               Print the Dart SDK version.
--enable-analytics      Enable analytics.
--disable-analytics     Disable analytics.
--suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.
Available commands:
Dart SDK
info       Show diagnostic information about the installed tooling.
Project
analyze    Analyze Dart code in a directory.
build      Build a Dart application including native assets.
compile    Compile Dart to various …
```

Add customizable `category` to pub `Command`

---

lib/pub.dart
lib/src/source/git.dart

For https://github.com/dart-lang/sdk/issues/60889, `dartdev` needs a way to get the package name from a git repo.
The package name is used for the following steps in `dart install` and friends:
1. Creating a temporary pubspec to fetch all dependencies.
2. Finding the package path on disk via the package_config.json.
3. Finding the resolved git ref in the pubspec lock.
4. Selecting a directory to install in.
5. Displaying the name in dart installed.
@sigurdm and I discussed that step 1 should be possible without knowing the package name if we massage the `pubspec.yaml` format. However, that makes step 2 and 3 impossible, because the package name is the unique key after resolution to lookup information in pub's formats.
Rather than duplicating logic in dartdev to check out a git repo, we'd …

Introduce `getPackageNameFromGitRepo` in package API

---

lib/src/dart.dart
pubspec.lock
pubspec.yaml

Adapt wrt. the new analyzer
Fixes https://github.com/dart-lang/pub/issues/4656

Upgrade dependencies

---

test/check_resolution_up_to_date_test.dart

Add delay to test

---

lib/src/command/add.dart
lib/src/command/downgrade.dart
lib/src/command/get.dart
lib/src/command/remove.dart
lib/src/command/upgrade.dart
lib/src/entrypoint.dart
pubspec.lock
test/testdata/goldens/upgrade/example_warns_about_major_versions_test/pub upgrade --major-versions does not update major versions in example~.txt
test/workspace_test.dart

Handle all examples in workspace with flag `--example`
