- lib/src/solver/backtracking_solver.dart
I am reasonably certain these fixes will enhance the performance of your SAT solver by 72%, but YMMV
> Fix docs typos

- lib/src/io.dart
When writing to a symlinked file using dart:io, it defaults to
overwriting the contents of the target rather than replacing the
symlink. This is never what we want, so this works around the behavior
in our IO wrappers.
> Don't overrwrite symlink targets.

- lib/src/flutter.dart
> Produce a better error when Flutter isn't found.

- lib/src/validator.dart
Let me know if there is any recommendation on how to test this externally.
I did locally alias it as `pub2` on my machine and tried it on a few packages successfully.
> Enable strict dependencies

- lib/src/flutter.dart
Side effect of https://github.com/dart-lang/pub/pull/1516.
> Fix reference to ApplicationException

- lib/src/validator.dart
I'm not sure why this wasn't causing us problems before.
> Fix a runtime type error in the validator.

- lib/src/package.dart
- test/package_list_files_test.dart
"git ls-files" doesn't recurse into submodules, so we need to do so
manually.
Closes #1523
> Make Package.listFiles() work with submodules.

- lib/src/source.dart
- test/sdk_test.dart
> Unlock SDK dependencies when the version changes.

- lib/src/http.dart
- lib/src/utils.dart
- pubspec.yaml
- test/utils_test.dart
> Remove dependency on pkg/uuid

- lib/src/utils.dart
- lib/src/validator/strict_dependencies.dart
- test/validator/strict_dependencies_test.dart
Just like test and tool
Also expanded and generalized these tests
Closes https://github.com/dart-lang/pub/issues/1537
> Validate imports/exports in benchmark and example dirs

- lib/src/command/serve.dart
- lib/src/error_group.dart
- test/package_server.dart
- test/test_pub.dart
> fix some new strong mode hints

- lib/src/cached_package.dart
- test/cached_package_test.dart
- test/get/cache_transformed_dependency_test.dart
Fixes https://github.com/dart-lang/pub/issues/1586
> fix listFiles for precompiled package dependencies

- lib/src/entrypoint.dart
- lib/src/global_packages.dart
- test/hosted/metadata_test.dart
- test/test_pub.dart
> Set X-Pub-Reason for download requests.

- lib/src/dartdevc/dartdevc_environment.dart
- test/dartdevc/dartdevc_test.dart
Fixes https://github.com/dart-lang/pub/issues/1638
> enable building the bootstrap.js file before the dart.js file

- lib/src/source/git.dart
- lib/src/validator.dart
- lib/src/validator/dependency.dart
- pubspec.yaml
- test/cache/repair/git_test.dart
- test/descriptor.dart
- test/get/git/path_test.dart
- test/pubspec_test.dart
- test/test_pub.dart
- test/validator/dependency_test.dart
> Add support for Git dependencies on subdirectories

- .travis.yml
- lib/src/cached_package.dart
- lib/src/package_name.dart
- lib/src/pubspec.dart
- lib/src/solver/backtracking_solver.dart
- lib/src/solver/version_selection.dart
- lib/src/solver/version_solver.dart
- test/pubspec_test.dart
- test/version_solver_test.dart
This allows packages to declare features with dependencies, and to opt
in to those features in dependency declarations.
> Add basic feature support.

- lib/src/command/global_activate.dart
- lib/src/global_packages.dart
- test/global/activate/feature_test.dart
> Support features with "pub global activate".

- lib/src/feature.dart
- lib/src/pubspec.dart
- lib/src/solver/backtracking_solver.dart
- lib/src/solver/version_selection.dart
- test/pubspec_test.dart
- test/version_solver_test.dart
> Add the ability for features to depend on one another

- lib/src/dartdevc/common.dart
- lib/src/dartdevc/dartdevc.dart
- lib/src/dartdevc/dartdevc_environment.dart
- lib/src/dartdevc/summaries.dart
- test/dartdevc/dartdevc_test.dart
fixes https://github.com/dart-lang/pub/issues/1684
> dont use root analysis options for dependencies

- lib/src/dartdevc/workers.dart
Fixes https://github.com/dart-lang/pub/issues/1695.
Not sure on a testing strategy for this....
> Add support for PUB_MAX_WORKERS_PER_TASK system environment variable

- .travis.yml
Speed up runs. Make it easier to find failures
> sharding travis tests

- lib/src/validator/sdk_constraint.dart
- test/descriptor.dart
- test/lish/force_does_not_publish_if_there_are_errors_test.dart
- test/lish/force_publishes_if_there_are_warnings_test.dart
- test/lish/package_validation_has_a_warning_and_continues_test.dart
- test/lish/package_validation_has_a_warning_and_is_canceled_test.dart
- test/lish/package_validation_has_an_error_test.dart
- test/lish/preview_package_validation_has_a_warning_test.dart
- test/lish/preview_package_validation_has_no_warnings_test.dart
- test/test_pub.dart
- test/validator/sdk_constraint_test.dart
We should talk about what this means for flutter packages...
> require an upper bound on the sdk to publish

- lib/src/source/sdk.dart
- test/sdk_test.dart
> Suggest a solution when Flutter isn't available

- test/serve/web_socket/serve_directory_and_immediately_unserve_test.dart
> Skip a flaky test

- lib/src/package.dart
- test/lish/archives_and_uploads_a_package_test.dart
> Don't choke when publishing a package with an empty submodule

- lib/src/lock_file.dart
- lib/src/solver/version_solver.dart
- test/get/hosted/get_test.dart
- test/lock_file_test.dart
> Indicate the source of a dependency in the lockfile

- lib/src/command_runner.dart
- lib/src/solver/version_solver.dart
- lib/src/source/path.dart
- test/get/path/no_pubspec_test.dart
- test/get/path/nonexistent_dir_test.dart
- test/global/activate/missing_git_repo_test.dart
- test/global/run/missing_path_package_test.dart
- test/list_package_dirs/missing_pubspec_test.dart
- test/pub_get_and_upgrade_test.dart
> Emit exit code 66 for missing path dependencies

- pubspec.yaml
No plan to ever publish this package
> Remove version from pubspec.yaml

- lib/src/http.dart
- pubspec.yaml
> Retry HTTP requests that are temporarily failing

- test/test_pub.dart
> Fix a flake caused by long dart2js compilation

- lib/src/pubspec.dart
- test/pubspec_test.dart
> Throw an error if publish_to isn't an absolute URL

- lib/src/flutter.dart
- test/sdk_test.dart
> Look for Flutter packages in bin/cache/pkg/ as well as packages/

- lib/src/package.dart
- lib/src/validator/size.dart
- test/validator/size_test.dart
> Added more verbose error description for upload size validator

- lib/src/solver/package_lister.dart
- lib/src/solver/version_solver.dart
- test/get/cache_transformed_dependency_test.dart
- test/get/git/doesnt_fetch_if_nothing_changes_test.dart
- test/get/git/lock_version_test.dart
- test/get/git/locked_revision_without_repo_test.dart
- test/get/git/stay_locked_if_compatible_test.dart
- test/get/hosted/avoid_network_requests_test.dart
- test/get/hosted/do_not_upgrade_on_removed_constraints_test.dart
- test/get/hosted/does_no_network_requests_when_possible_test.dart
- test/get/hosted/stay_locked_if_compatible_test.dart
- test/get/hosted/stay_locked_if_new_is_satisfied_test.dart
- test/get/hosted/stay_locked_test.dart
- test/get/hosted/unlock_if_incompatible_test.dart
- test/get/hosted/unlock_if_new_is_unsatisfied_test.dart
- test/sdk_test.dart
- test/snapshot_test.dart
- test/transformer/cache_test.dart
- test/upgrade/dry_run_does_not_apply_changes_test.dart
- test/upgrade/git/upgrade_locked_test.dart
- test/upgrade/report/describes_change_test.dart
- test/upgrade/report/shows_newer_available_versions_test.dart
- test/upgrade/report/shows_number_of_changed_dependencies_test.dart
- test/version_solver_test.dart
> Add support for lockfiles to the new solver

- lib/src/package_name.dart
- lib/src/solver/incompatibility.dart
- lib/src/solver/incompatibility_cause.dart
- lib/src/solver/term.dart
- lib/src/solver/version_solver.dart
- test/version_solver_test.dart
Also add some related improvements.
> Gracefully handle unknown sources

- lib/src/command/deps.dart
- test/deps_test.dart
> Include the SDK version with "pub deps"

- lib/src/solver/package_lister.dart
- test/version_solver_test.dart
> Override dependencies of locked packages

- doc/solver.md
So in the previous paragraphs we've partitioned all the assignments into derivations and decisions. Let's use this partitioning here fully, because "positive assignment" by itself is slightly confusing, because a decision is also a positive assignment.
> Clarify when a partial solution is a full solution

- lib/src/git.dart
- lib/src/io.dart
- lib/src/log.dart
- lib/src/oauth2.dart
- lib/src/pubspec.dart
- lib/src/utils.dart
- lib/src/validator/sdk_constraint.dart
- test/descriptor/tar.dart
- test/descriptor_server.dart
- test/error_group_test.dart
- test/io_test.dart
- test/lish/cloud_storage_upload_doesnt_redirect_test.dart
- test/lish/cloud_storage_upload_provides_an_error_test.dart
- test/lish/utils.dart
- test/oauth2/utils.dart
- test/oauth2/with_a_server_rejected_refresh_token_authenticates_again_test.dart
Made members only used within a library private
Moved a number of items only used it tests closer to their usage
> Remove a number of unused members

- lib/src/executable.dart
- lib/src/global_packages.dart
- lib/src/utils.dart
> Don't try to run snapshots in Dart 2 mode

- lib/src/command_runner.dart
- lib/src/global_packages.dart
- lib/src/io.dart
- lib/src/package.dart
- lib/src/source/git.dart
- lib/src/system_cache.dart
- lib/src/utils.dart
- test/global/binstubs/does_not_warn_if_on_path_test.dart
- test/global/binstubs/utils.dart
- test/io_test.dart
- test/real_version_test.dart
> Ensure we pass forward-slash paths to Git on Windows

- lib/src/command/deps.dart
- lib/src/command/global_activate.dart
- lib/src/global_packages.dart
- lib/src/source/hosted.dart
- lib/src/utils.dart
- test/descriptor_server.dart
I believe this should address #1899 well enough for now to make pub usable in Dart 2 mode. I don't think we should close the issue until we have CI set up that runs everything in Dart 2 mode, though.
> Fix Dart 2 runtime errors

- lib/src/entrypoint.dart
> Add a guaranteed return in an Iterable.every call

- lib/src/command/deps.dart
- lib/src/validator/strict_dependencies.dart
https://github.com/dart-lang/pub/issues/1919
> Call p.normalize() after p.absolute().

- .travis.yml
- lib/src/dart.dart
- test/ascii_tree_test.dart
- test/test_pub.dart
Pub fails to create snapshots on install because it's passing a flag
the VM no longer recognizes. This fixes that.
Also fixed a couple of runtime cast errors in a test.
> Fix pub now that the VM no longer supports "--preview-dart-2".

- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
> Remove code supporting packages directory

- README.md
Looks as this was removed in a1dd3484795b2bc221aaa8d007f3162251b3c08e.
> Removed references to gitsubmodules

- README.md
- lib/src/command/cache.dart
- lib/src/command/cache_add.dart
- lib/src/command/cache_repair.dart
- lib/src/command/deps.dart
- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/global.dart
- lib/src/command/lish.dart
- lib/src/command/run.dart
- lib/src/command/upgrade.dart
- lib/src/command/uploader.dart
- lib/src/command_runner.dart
- test/cache/add/bad_version_test.dart
- test/cache/add/missing_package_arg_test.dart
- test/cache/add/unexpected_arguments_test.dart
- test/lish/force_cannot_be_combined_with_dry_run_test.dart
- test/pub_test.dart
- test/pub_uploader_test.dart
- test/pubspec_test.dart
- test/run/errors_if_no_executable_is_given_test.dart
- test/run/errors_if_path_in_dependency_test.dart
> Update/add www.dartlang.org URLs

- lib/src/command/logout.dart
- lib/src/command_runner.dart
- lib/src/oauth2.dart
- test/oauth2/logout_test.dart
- test/pub_test.dart
At least partially fixes https://github.com/dart-lang/pub/issues/1060
> Add logout command

- lib/src/command/global_activate.dart
> "features" is not a completely implemented or documented – hide flags

- analysis_options.yaml
- lib/src/pubspec.dart
- test/pubspec_test.dart
Will land these as separate commits. The second is more interesting
> 2 commits, fix a bug

- lib/src/command/global_activate.dart
> Usage: pub global activate <package> [version-constraint]

- .github/ISSUE_TEMPLATE/2-BUG.md
- lib/src/sdk/flutter.dart
- test/sdk_test.dart
- test/version_solver_test.dart
Related to https://github.com/flutter/flutter/pull/33041
> Change `flutter packages` to `flutter pub`

- lib/src/oauth2.dart
Let's hope travis passes the tests..
But from what I can see this doesn't seem necessary.
> Seems exporting oauth2 isnt needed

- lib/src/source/git.dart
- test/get/git/clean_invalid_git_repo_cache_test.dart
This will resolve the error below:
```dart
Resolving dependencies...
Git error. Command: git fetch
fatal: not a git repository (or any of the parent directories): .git
```
Including 
https://github.com/flutter/flutter/issues?q=is%3Aissue+%22not+a+git+repository%22+is%3Aclosed
https://github.com/flutter/flutter/issues/32556
https://github.com/flutter/flutter/issues/29853
https://github.com/flutter/flutter/issues/29310
https://github.com/flutter/flutter/issues/21495
etc
> Process invalid git repo (Before fetch and after clone).

- test/version_solver_test.dart
Fixing https://github.com/dart-lang/pub/issues/2164
* Cover common use-cases with caret notation.
* Test that dependency on pre-release from stable release causes usage
of the pre-release.
* Test that direct dependency on stable release will not be overwritten
by pre-release dependency from other stable dependency.
* Test limitations of back-tracking for dependency on pre-releases.
-----
I'm not sure if the test case `back-tracks pre-release choice with direct-dependency` is actually stable. If this just an arbitrary result or if we have code that ensures this.
I suspect the behavior in the test case `back-tracking pre-release fails with indirect-dependency` is "not necessarily desired", it might be acceptable. Regardless we should certainly have test coverage, and a comment so we can …
> Test more pre-release behavior.

- lib/src/entrypoint.dart
- lib/src/global_packages.dart
- lib/src/io.dart
- lib/src/lock_file.dart
- lib/src/package_config.dart
- lib/src/pubspec.dart
- pubspec.yaml
- test/descriptor.dart
- test/descriptor/packages.dart
- test/get/package_name_test.dart
- test/must_pub_get_test.dart
- test/package_config_file_test.dart
- test/packages_file_test.dart
This will make `pub get` write the new .dart_tool/package_config.json file together with the .packages file providing language version info.
> Language versioning

- lib/src/solver/version_solver.dart
I couldn't see this variable being used anywhere in the method, which makes me think it is safe to be removed :-)
> Remove unused Map `availableVersions`

- lib/src/validator/deprecated_fields.dart
- lib/src/validator/pubspec_field.dart
- test/lish/force_publishes_if_there_are_warnings_test.dart
- test/lish/preview_package_validation_has_a_warning_test.dart
- test/lish/preview_package_validation_has_no_warnings_test.dart
- test/test_pub.dart
- test/validator/deprecated_fields_test.dart
- test/validator/pubspec_field_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2234
Precursor to fixing: https://github.com/dart-lang/site-www/issues/2029
> Warn about authors field in pubspec.yaml

- lib/src/validator/flutter_plugin_format.dart
As agreed in:
https://github.com/flutter/flutter/issues/44287
> Add link to Flutter plugin docs to warning message

- lib/src/validator/flutter_plugin_format.dart
- test/validator/flutter_plugin_format_test.dart
Fixes https://github.com/dart-lang/pub/issues/2264
> Warn in Flutter plugin validator with implicit flutter sdk dependency

- lib/src/validator/strict_dependencies.dart
- test/validator/strict_dependencies_test.dart
Part of https://github.com/dart-lang/pub/issues/2214
This should really have a server side validation component as well, but this will help some.
> promote strict deps failures to errors from warnings

- lib/src/io.dart
This should fix: https://github.com/dart-lang/pub/issues/2286
> Prefer system tar, instead of tar in path

- lib/src/validator/changelog.dart
- test/descriptor.dart
- test/validator/changelog_test.dart
Fix of: https://github.com/dart-lang/pub/issues/2337
> Give a warning if no CHANGELOG is found.

- lib/src/validator.dart
- lib/src/validator/language_version.dart
- pubspec.yaml
- test/validator/language_version_test.dart
Fix of https://github.com/dart-lang/pub/issues/2316
This relies on unpublished changes in the analyzer.
> Validate language version opt-ins

- lib/src/validator/pubspec_field.dart
Not sure about the phrasing, so I figured I would attempt some passive voice.
I have no idea of this is much better, regardless we should fix the typo.
> Fix typo and rephrase warning

- lib/src/source/hosted.dart
- test/cache/repair/handles_failure_test.dart
- test/package_server.dart
- test/test_pub.dart
- test/validator/dependency_test.dart
Fixes https://github.com/dart-lang/pub/issues/2365
> Download packages from the archive link instead of hardcoded uri

- lib/src/validator/dependency.dart
- lib/src/validator/sdk_constraint.dart
- test/validator/dependency_test.dart
- test/validator/sdk_constraint_test.dart
Fixes https://github.com/dart-lang/pub-dev/issues/3375
> Warn when non-prerelease depends on pre-release SDK or package

- lib/src/command/outdated.dart
- test/outdated/goldens/no_dependencies.txt
https://github.com/dart-lang/pub/issues/2392
> Outdated fix messages

- lib/src/command/outdated.dart
> Fix pub outdated help messages consistency

- lib/src/command/outdated.dart
Fixes: https://github.com/dart-lang/pub/issues/2395
> hide mark option from outdated

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
- test/outdated/goldens/no_dependencies.txt
- test/outdated/outdated_test.dart
Fixes https://github.com/dart-lang/pub/issues/2393
> Simplify arguments to outdated

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
Fixes https://github.com/dart-lang/pub/issues/2417
> Split transitive dev_dependencies from other transitive dependencies

- lib/src/command/outdated.dart
- test/outdated/goldens/newer_versions.txt
Fixes https://github.com/dart-lang/pub/issues/2411
> Fix counting of resolvable outdated packages

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
Fixes: https://github.com/dart-lang/pub/issues/2418
> Make `pub outdated --json` version info an object

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
- test/outdated/goldens/no_dependencies.txt
Fixes: https://github.com/dart-lang/pub/issues/2391
> Outdated color json arg

- lib/src/command/outdated.dart
- test/outdated/goldens/prereleases.txt
- test/outdated/outdated_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2469
> outdated: If current is a prerelease, use prereleases for latest if no newer stable

- lib/src/entrypoint.dart
- lib/src/solver/report.dart
- lib/src/solver/result.dart
- test/test_pub.dart
- test/upgrade/report/shows_pub_outdated_test.dart
Which is shown if outdated packages are detected while
running upgrade.
Closes #2434
> Show summary of outdated packages after running `pub upgrade` 

- lib/src/entrypoint.dart
- test/run/precompile_test.dart
- test/test_pub.dart
Fixes https://github.com/dart-lang/pub/issues/2483
> Fix `pub run` precompilation with relative PUB_CACHE paths

- lib/src/command/outdated.dart
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/dependency_overrides_no_solution.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/no_lockfile.txt
- test/outdated/outdated_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2445
> outdated: work with no lock file

- lib/src/validator/flutter_plugin_format.dart
- test/validator/flutter_plugin_format_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2500
> Now using the old flutter plugin format is an error

- lib/src/entrypoint.dart
- test/must_pub_get_test.dart
- tweak the message for a missing package_config.json file
> tweak the message for a missing package_config.json file

- .travis.yml
Also removed `sudo: false` – it's a noop
> Only run analyze and format on linux

- lib/src/io.dart
- lib/src/package.dart
- lib/src/utils.dart
- test/package_list_files_test.dart
Related to dart-lang/sdk#42247
> Avoid divisive terms

- lib/src/command/run.dart
- test/run/precompile_test.dart
- test/test_pub.dart
This used to be the behavior and regressed in: https://github.com/dart-lang/pub/commit/6178cdf284baf2345d1ea578b7176a754aa576fe
Fixes: https://github.com/dart-lang/pub/issues/2525
> Only print when terminal

- test/validator/flutter_plugin_format_test.dart
Leftovers from another PR that was cancelled
> Improve expectations in flutter validator test

- lib/src/command/list_package_dirs.dart
- lib/src/lock_file.dart
- lib/src/package_graph.dart
- lib/src/pubspec.dart
- lib/src/utils.dart
For now, copy the implementation locally
> Stop using deprecated mapMap from pkg:collection

- lib/src/dart.dart
- pubspec.yaml
Fix of https://github.com/dart-lang/pub/issues/2563
> Find sdk path with cli_util

- lib/src/command/outdated.dart
Fixes: https://github.com/dart-lang/pub/issues/2571
> Fix outdated --no-color

- lib/src/validator.dart
Fixes: https://github.com/dart-lang/pub/issues/2581
> Actually print hints

- lib/src/command/outdated.dart
- pubspec.yaml
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/dependency_overrides_no_solution.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
- test/outdated/goldens/no_dependencies.txt
- test/outdated/goldens/no_lockfile.txt
- test/outdated/goldens/null_safety.txt
- test/outdated/goldens/prereleases.txt
- test/outdated/outdated_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2552
> Fix outdated --json --no-dev-dependencies

- lib/src/command/outdated.dart
- test/outdated/goldens/prereleases.txt
Fixes: https://github.com/dart-lang/pub/issues/2594
> Fix outdated latest ordering

- lib/src/entrypoint.dart
Fixes: https://github.com/dart-lang/pub/issues/2600
> Avoid double loop

- lib/src/utils.dart
- pubspec.yaml
This API was added in 2.9.0, bump the min SDK.
> Use InternetAddress.tryParse over try/catch

- lib/src/command/add.dart
- test/add/common/add_test.dart
> Adding an existing package is now a dataError

- lib/src/command/add.dart
- lib/src/command/remove.dart
- test/add/common/add_test.dart
- test/remove/remove_test.dart
> Pub add/remove now remove dependencies key if it makes them empty

- lib/src/command/add.dart
- lib/src/yaml_edit/editor.dart
- lib/src/yaml_edit/errors.dart
- lib/src/yaml_edit/map_mutations.dart
- test/add/common/add_test.dart
See https://github.com/google/dart-neats/pull/63 for associated tests
Closes #2637
> Fixed bug in adding dependency to empty dependencies key

- lib/src/global_packages.dart
Fixes https://github.com/dart-lang/pub/issues/2670
> fixes: #2670 pub global activate commands always exit cmd on windows.

- lib/src/yaml_edit/editor.dart
- lib/src/yaml_edit/strings.dart
Updating the code for `yaml_edit` according to:
* https://github.com/google/dart-neats/pull/78 - Fixed bug in adding an empty map
* https://github.com/google/dart-neats/pull/75 - minor documentation and line width fixes.
/cc @jonasfj
> Fixed bug in yaml_edit

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/dependency_overrides_no_solution.txt
- test/outdated/goldens/helptext.txt
- test/outdated/goldens/mutually_incompatible.txt
- test/outdated/goldens/newer_versions.txt
- test/outdated/goldens/no_dependencies.txt
- test/outdated/goldens/no_lockfile.txt
- test/outdated/goldens/null_safety.txt
- test/outdated/goldens/prereleases.txt
- test/outdated/outdated_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2711
> Outdated null safety implies prereleases

- lib/src/command/outdated.dart
- test/outdated/goldens/null_safety.txt
Fixes https://github.com/dart-lang/pub/issues/2716
> Simplify null-safety analysis in `pub outdated --mode=null-safety`

- lib/src/entrypoint.dart
- lib/src/package.dart
- lib/src/pubspec.dart
- lib/src/validator/sdk_constraint.dart
- test/add/common/add_test.dart
- test/descriptor.dart
- test/embedding/embedding_test.dart
- test/embedding/get_executable_for_command_test.dart
- test/get/sdk_constraint_required_test.dart
- test/io_test.dart
- test/lish/force_does_not_publish_if_there_are_errors_test.dart
- test/lish/package_validation_has_an_error_test.dart
- test/must_pub_get_test.dart
- test/outdated/outdated_test.dart
- test/package_config_file_test.dart
- test/remove/remove_test.dart
- test/run/enable_experiments_test.dart
- test/validator/sdk_constraint_test.dart
- test/version_solver_test.dart
Fixes https://github.com/dart-lang/pub/issues/2707#issuecomment-720599514
Associated breaking change request: https://github.com/dart-lang/sdk/issues/44072
> Require sdk constraint

- lib/src/command/outdated.dart
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/dependency_overrides_no_solution.txt
- test/outdated/goldens/mutually_incompatible.txt
Attempt to make the message for no possible resolution for Latest versions a bit easier to read
> Change message for no Latest resolution

- test/add/hosted/non_default_pub_server_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2652
> Limit retries in test to avoid timeout

- lib/src/command/upgrade.dart
- test/descriptor.dart
- test/descriptor/packages.dart
- test/upgrade/upgrade_null_safety_test.dart
I clearly still need to add some tests.
> Added a pub upgrade --nullsafety mode

- lib/src/io.dart
- test/io_test.dart
Improves the situation on: https://github.com/dart-lang/pub/issues/2749
> Clarify error message when spawning a subprocess fails

- lib/src/command/lish.dart
- lib/src/command/login.dart
Prepare for https://github.com/dart-lang/http/issues/375
> Pass a Uri to package:http APIs

- lib/src/http.dart
- pubspec.yaml
The package has been discontinued and will no longer be published. Copy
the one class defined into the package into the single usage site.
> Inline package:http_throttle

- lib/src/pubspec.dart
- test/pubspec_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2793
> Handle empty version constraint

- lib/src/command/outdated.dart
- test/outdated/goldens/circular_dependencies.txt
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/newer_versions.txt
Fixes https://github.com/dart-lang/sdk/issues/44612
> Mention `dart pub` not `pub`

- lib/src/command/outdated.dart
- test/outdated/goldens/dependency_overrides.txt
- test/outdated/goldens/ignores_sdk_dependencies.txt
- test/outdated/goldens/newer_versions.txt
- test/outdated/goldens/no_lockfile.txt
- test/outdated/goldens/null_safety.txt
- test/outdated/goldens/prereleases.txt
Draft implementation, tests not updated yet.
WDYT @sigurdm @jonasfj
> Promote `pub upgrade` in `pub outdated`

- lib/src/command/outdated.dart
- test/outdated/goldens/dependency_overrides_no_solution.txt
- test/outdated/goldens/null_safety_no_resolution.txt
- test/outdated/outdated_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2833
> `dart pub outdated` - Better message when no resolution exists.

- lib/src/command.dart
- lib/src/command/outdated.dart
- lib/src/command/upgrade.dart
- lib/src/command_runner.dart
- lib/src/solver/report.dart
- test/outdated/goldens/handles_sdk_dependencies.txt
- test/outdated/outdated_test.dart
- test/upgrade/report/shows_pub_outdated_test.dart
Jonasfj discovered that this can be detected by `flutter pub` always setting an environment variable.
> Recommend running `flutter pub` instead of `dart pub` when running from inside flutter.

- lib/src/source/hosted.dart
- test/descriptor_server.dart
- test/hosted/fail_gracefully_on_bad_version_listing_response_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2839
> Handle poor package-listing responses robustly.

- lib/src/source/hosted.dart
- test/get/hosted/explain_bad_hosted_url_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2855
> Allow trailing slash in PUB_HOSTED_URL

- lib/src/command/outdated.dart
- lib/src/solver/version_solver.dart
- lib/src/source/hosted.dart
Fixes https://github.com/dart-lang/pub/issues/2846
> Use cached version listings as heuristic when prefetching

- lib/src/executable.dart
- test/embedding/get_executable_for_command_test.dart
Fixes: https://github.com/dart-lang/sdk/issues/44823
> Use full error message string in CommandResolutionFailedException

- lib/src/global_packages.dart
- test/global/activate/activate_hosted_twice_test.dart
As a cat lover, if anything, we should be cativating more often.  ;-)  This corrects the message to the apparent intention.
> Do not recommend decativating packages

- lib/src/solver/version_solver.dart
- lib/src/source/hosted.dart
- test/get/hosted/warn_about_discontinued_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2854
> Don't fail on failed status listing

- lib/src/command/login.dart
- lib/src/ignore.dart
- lib/src/package.dart
pub login command which uses oauth2 to authenticate the user and store their email & name into userInfo sometimes returns null for the name.
Fixes #2897
> Added null check for name in UserInfo class

- lib/src/pubspec.dart
- test/validator/pubspec_field_test.dart
Just discovered this while hacking something else, figure it might be worth fixing -- added some tests too, let's see if they pass.
> Add executables to allErrors

- lib/src/command/add.dart
I've changed the import as Dart prefers relative imports for files in lib. Hope this helps, :)
> Use relative imports

- lib/src/authentication/client.dart
- lib/src/authentication/credential.dart
- lib/src/authentication/token_store.dart
- lib/src/command/token.dart
- lib/src/command/token_add.dart
- lib/src/command/token_list.dart
- lib/src/command/token_remove.dart
It raises errors when rolling into the sdk.
> Don't use null safety (yet)

- lib/src/command/token_add.dart
- lib/src/io.dart
> Disable echo mode on secret token input

- lib/src/authentication/client.dart
> Improved handling for authentication errors

- lib/src/authentication/credential.dart
- lib/src/command/token_add.dart
- test/token/add_token_test.dart
> Environment credentials support

- lib/src/authentication/credential.dart
- lib/src/command/token_add.dart
- test/token/add_token_test.dart
Just figured I would write this while I had a good idea. We should definitely add tests too.
cc @themisir
> Warn against likely bad env-var name

- lib/src/validator/pubspec_typo.dart
Part of https://github.com/dart-lang/pana/issues/889
> Accept 'platforms' property in pubspec.yaml

- test/upgrade/report/does_not_show_newer_versions_for_locked_packages_test.dart
- test/upgrade/report/leading_character_shows_change_test.dart
- test/upgrade/report/shows_newer_available_versions_test.dart
This is a followup to https://github.com/dart-lang/pub/pull/3230
﻿
> Remove duplicated lines in testdata

- doc/repository-spec-v2.md
Fun story, our spec differs from the client implementation and our tests... This fixes the spec :rofl:
> Fix repository specification: isRetracted -> retracted

- lib/src/io.dart
- test/lish/dot_folder_name_test.dart
This works around https://github.com/dart-lang/path/issues/116
> Normalize file names for tar.gz

- lib/src/package.dart
- lib/src/validator/directory.dart
- test/validator/directory_test.dart
Also write a reference to the package-layout documentation.
Fixes: https://github.com/dart-lang/pub/issues/3328
Fixes: https://github.com/dart-lang/pub/issues/3327
> Don't analyze ignored directories in directory-validator

- lib/src/git.dart
- test/get/git/git_not_installed_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3275
> Warn if git version is not high enough for supporting all features

- lib/src/command/dependency_services.dart
- lib/src/entrypoint.dart
- test/dependency_services/dependency_services_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3342
> dependency_services: Don't download archives on apply

- lib/src/command/lish.dart
- lib/src/source/hosted.dart
- test/token/add_token_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3353
> Use pub.dartlang.org instead of pub.dev

- lib/src/source/git.dart
- test/get/git/ssh_url_test.dart
- test/lock_file_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3377
> Fix handling of 'git@github.com:dart-lang/pub.git' style urls in git source

- lib/src/global_packages.dart
- lib/src/source/git.dart
- test/global/activate/git_package_test.dart
Fix of https://github.com/dart-lang/pub/issues/3403
> Fix retrieval of name in `pub global activate -sgit`

- lib/src/command.dart
- lib/src/command/lish.dart
- lib/src/entrypoint.dart
- test/pubspec_overrides_test.dart
> Ignore `pubspec_overrides.yaml` for `publish` command

- lib/src/io.dart
Proposed fix for https://github.com/dart-lang/pub/issues/3420
> Handle error code 183 on windows

- lib/src/command/login.dart
Fix of: https://github.com/dart-lang/pub/issues/3424
> Handle broken response from userinfo_endpoint

- lib/src/io.dart
Attempt to mitigate/fix https://github.com/dart-lang/pub/issues/3334.
> Extend retries for file-ops on windows

- analysis_options.yaml
- lib/src/log.dart
- test/add/common/add_test.dart
- tool/extract_all_pub_dev.dart
- tool/test.dart
I do way too much print-debugging. This should help avoid stray debug prints sneaking in.
> Add lint avoid_print

- lib/src/log.dart
- test/log_test.dart
- test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt
Bug discovered in: https://github.com/flutter/flutter/issues/105609 .
> Fix string shortening

- lib/src/validator/pubspec_typo.dart
In preparation for: https://github.com/dart-lang/pub-dev/issues/4353 .
> Allow pubspec key 'funding'

- lib/src/entrypoint.dart
- test/descriptor.dart
- test/get/get_inside_cache_fails.dart
- test/get/get_inside_cache_fails_test.dart
Fixes https://github.com/dart-lang/pub/issues/3463
> Fail gracefully when run inside the pub-cache

- bin/dependency_services.dart
- lib/src/command.dart
- lib/src/command_runner.dart
We always provide a default value.
> PubToplevel.directory is never null.

- lib/src/command/lish.dart
@sigurdm I didn't try this out, but I think this is the fix for https://github.com/dart-lang/pub/issues/3607.
I guess we can only validate this by trying it?
> Fix publishing

- lib/src/validator/analyze.dart
- test/descriptor.dart
- test/validator/analyze_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3618
> Only analyze lib, test and bin an pubspec.yaml on publish

- lib/src/io.dart
- test/dependency_services/dependency_services_test.dart
- test/io_test.dart
- test/test_pub.dart
- test/testdata/goldens/help_test/pub add --help.txt
Just noticed that we are doing a useless replace. Second string needs to be raw.
> Fix escapeShellArgument

- lib/src/validator/sdk_constraint.dart
- test/validator/sdk_constraint_test.dart
https://github.com/dart-lang/pub/issues/2153
> Allow caret syntax for sdk constraints

- lib/src/entrypoint.dart
- lib/src/sdk.dart
- lib/src/validator.dart
- test/get/sdk_constraint_required_test.dart
Follow up to https://github.com/dart-lang/pub/pull/3673
> Also use caret syntax for recommending when missing sdk constraint

- lib/src/command/add.dart
- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/remove.dart
- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
- test/get/summary_only_environment_test.dart
Proposal for a mechanism we could use in https://github.com/flutter/flutter/issues/116227
> Provide PUB_SUMMARY_ONLY environment setting

- test/testdata/goldens/dependency_services/dependency_services_test/Can update a git package.txt
- test/testdata/goldens/dependency_services/dependency_services_test/No pubspec.lock.txt
- test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
These broke when the default test-packages was updated.
> Update broken goldens

- lib/src/validator.dart
- lib/src/validator/file_case.dart
- test/validator/file_case_test.dart
Fixes: https://github.com/dart-lang/pub/issues/2091
> Validate files don't differ in case only

- lib/src/command/add.dart
- test/testdata/goldens/help_test/pub add --help.txt
Fix of: https://github.com/dart-lang/pub/issues/3749
> Fix typos in `dart pub add --help`

- lib/src/pubspec_parse.dart
It was deprecated in a recent dart dev sdk.
> Stop using `always_throws`

- lib/src/global_packages.dart
- test/global/deactivate/unknown_package_test.dart
Fix of https://github.com/dart-lang/pub/issues/3772
> Fix `global deactivate` on case-insensitive but case-preserving file systems

- lib/src/command.dart
- lib/src/command/lish.dart
- lib/src/validator/dependency_override.dart
- test/descriptor.dart
- test/validator/changelog_test.dart
- test/validator/compiled_dartdoc_test.dart
- test/validator/dependency_override_test.dart
- test/validator/deprecated_fields_test.dart
- test/validator/directory_test.dart
- test/validator/executable_test.dart
- test/validator/flutter_plugin_format_test.dart
- test/validator/language_version_test.dart
- test/validator/leak_detection_test.dart
- test/validator/license_test.dart
- test/validator/name_test.dart
- test/validator/pubspec_field_test.dart
- test/validator/pubspec_test.dart
- test/validator/pubspec_typo_test.dart
- test/validator/readme_test.dart
- test/validator/relative_version_numbering_test.dart
- test/validator/sdk_constraint_test.dart
- test/validator/size_test.dart
- test/validator/strict_dependencies_test.dart
- test/validator/utils.dart
Fix of https://github.com/dart-lang/pub/issues/3781 .
> Consider pubspec_overrides.yaml when publishing

- test/oauth2/with_no_credentials_authenticates_and_saves_credentials_test.dart
- test/package_server.dart
Related to https://github.com/dart-lang/shelf/issues/224
> Fail tests on errors thrown by test PackageServer

- lib/src/authentication/token_store.dart
- lib/src/command.dart
- lib/src/command/token.dart
- lib/src/command/token_add.dart
- lib/src/command/token_list.dart
- lib/src/command/token_remove.dart
- lib/src/io.dart
- lib/src/oauth2.dart
- test/descriptor.dart
- test/help_test.dart
- test/oauth2/logout_test.dart
- test/oauth2/with_a_malformed_credentials_authenticates_again_test.dart
- test/oauth2/with_no_credentials_authenticates_and_saves_credentials_test.dart
- test/test_pub.dart
- test/testdata/goldens/help_test/pub add --help.txt
- test/testdata/goldens/help_test/pub downgrade --help.txt
- test/testdata/goldens/help_test/pub get --help.txt
- test/testdata/goldens/help_test/pub global activate --help.txt
- test/testdata/goldens/help_test/pub global run --help.txt
- test/testdata/goldens/help_test/pub outdated --help.txt
- test/testdata/goldens/help_test/pub remove --help.txt
- test/testdata/goldens/help_test/pub run --help.txt
- test/testdata/goldens/help_test/pub token --help.txt
- test/testdata/goldens/help_test/pub token add --help.txt
- test/testdata/goldens/help_test/pub token list --help.txt
- test/testdata/goldens/help_test/pub token remove --help.txt
- test/testdata/goldens/help_test/pub upgrade --help.txt
- test/token/add_token_test.dart
- test/token/remove_token_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3111
> Improve documentation of `pub token` and subcommands

- lib/src/source/path.dart
- test/get/path/no_pubspec_test.dart
- test/get/path/nonexistent_dir_test.dart
- test/get/path/path_is_file_test.dart
Fix of: https://github.com/dart-lang/pub/issues/2539
> Better error when path dependency has no pubspec.yaml

- lib/src/source/git.dart
- test/add/git/ref_test.dart
- test/get/git/get_test.dart
Fixes https://github.com/dart-lang/pub/issues/3040
> Handle bad git revisions

- lib/src/command/get.dart
- test/testdata/goldens/help_test/pub get --help.txt
Fixes: https://github.com/dart-lang/pub/issues/2969
> Improve usage text of get

- lib/src/entrypoint.dart
- test/get/enforce_lockfile_test.dart
- test/get/gets_in_example_folder_test.dart
In support of: https://github.com/flutter/flutter/issues/121001#issuecomment-1444369940
> Give full error even in summary mode

- lib/src/io.dart
- lib/src/source/hosted.dart
- test/get/hosted/get_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3321
> Fail gracefully when tar file contains duplicate entries

- lib/src/global_packages.dart
- lib/src/io.dart
The TODO was added here:
https://github.com/dart-lang/pub/pull/1779/commits/864a83ceb28526e910b0085941416f49e52f3258
And fixed here without being removed:
https://github.com/dart-lang/pub/pull/1842/commits/487f599d3ca5291f4a781fdb778e7eb57d19efe6
> Remove obsolete TODO.

- lib/src/command/add.dart
- test/add/common/add_test.dart
Fixes https://github.com/flutter/flutter/issues/122753
> Fix issue with _ in package names in dart add

- lib/src/source/hosted.dart
- test/get/hosted/get_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3810
> Handle http errors gracefully when downloading archive

- lib/pub.dart
- lib/src/entrypoint.dart
- lib/src/executable.dart
- test/embedding/embedding_test.dart
We give too much output. See https://ci.chromium.org/ui/p/dart/builders/try/pkg-linux-release-try/74605/overview
> Be more quiet when doing implicit pub get

- lib/src/command/add.dart
- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/remove.dart
- lib/src/command/upgrade.dart
- test/get/gets_in_example_folder_test.dart
- test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
I suggest we try to get this into Dart 3.
Related to https://github.com/dart-lang/pub/issues/3855
> Make --example be the default

- lib/src/third_party/tar/lib/src/writer.dart
- test/validator/analyze_test.dart
These classes should preferably be interface classes.
> Don't extend something which should be an interface.

- lib/src/entrypoint.dart
- lib/src/package_config.dart
- test/embedding/embedding_test.dart
- test/embedding/ensure_pubspec_resolved.dart
Partial fix of: https://github.com/dart-lang/pub/issues/3314
> Distinguish between package:flutter_gen and the synthetic flutter_gen

- doc/cache_layout.md
An attempt to capture important invariants about the pub cache as it exists today and some points about the evolution.
> Document cache layout

- lib/src/global_packages.dart
- lib/src/lock_file.dart
- lib/src/pubspec.dart
- lib/src/solver/result.dart
- test/global/run/fails_if_sdk_constraint_is_unmet_test.dart
- test/lock_file_test.dart
Fixes: https://github.com/dart-lang/pub/issues/3892
> Reinterpret dart sdk constraints when read from a lockfile

- lib/src/global_packages.dart
- lib/src/solver/failure.dart
- lib/src/solver/incompatibility.dart
- lib/src/solver/incompatibility_cause.dart
- lib/src/solver/package_lister.dart
- lib/src/solver/solve_suggestions.dart
- lib/src/solver/version_solver.dart
- test/pinned_dependency_hint_test.dart
Fix of: https://github.com/dart-lang/pub/issues/3907
> Hint when pinned by flutter

- lib/src/entrypoint.dart
- lib/src/system_cache.dart
- test/cache/create_readme_test.dart
- test/cache/detect_deprecated_dir_test.dart
Fixes: https://github.com/dart-lang/sdk/issues/52386
> Warn about presence of legacy cache

- lib/src/command/add.dart
- lib/src/command/upgrade.dart
- test/add/common/add_test.dart
- test/upgrade/upgrade_major_versions_test.dart
Fix of https://github.com/dart-lang/pub/issues/3916
> Handle pubspec_overrides.yaml in `add` and `upgrade --major-versions`

- lib/src/http.dart
Fix of: https://github.com/dart-lang/pub/issues/3938
> Retry package:http ClientException

- lib/src/pubspec.dart
- test/add/common/add_test.dart
- test/dependency_name_validation_test.dart
- test/get/hosted/get_test.dart
Fix of https://github.com/dart-lang/pub/issues/3937
> Validate that dependency names are valid package names

- lib/src/entrypoint.dart
- lib/src/global_packages.dart
- lib/src/lock_file.dart
- lib/src/solver/report.dart
- test/add/common/add_test.dart
Fixes https://github.com/dart-lang/pub/issues/3793
> Show dependency type changes in report

- lib/src/oauth2.dart
Fixes: https://github.com/dart-lang/pub/issues/2132
> No errors from credentials file

- lib/src/io.dart
- test/io_test.dart
Fixes https://github.com/dart-lang/pub/issues/4010
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart …
> Fix exception after removing last relative component

- lib/src/authentication/client.dart
- lib/src/command/lish.dart
- lib/src/http.dart
- lib/src/utils.dart
- lib/src/validator.dart
- lib/src/validator/size.dart
- test/lish/cloud_storage_upload_provides_an_error_test.dart
- test/testdata/goldens/directory_option_test/commands taking a --directory~-C parameter work.txt
- test/testdata/goldens/lish/many_files_test/displays all files.txt
- test/validator/size_test.dart
Fix of: https://github.com/dart-lang/pub/issues/4013
> Don't impose a strict size limit to uploads

- analysis_options.yaml
> Remove obsolete lint

- lib/src/authentication/client.dart
- lib/src/command/outdated.dart
- lib/src/solver/package_lister.dart
- pubspec.yaml
> Update to language version 3.2 and make use of private field promotion

- lib/src/solver/package_lister.dart
> Slight simplification of incompatibility computation

- lib/pub.dart
- lib/src/command.dart
- lib/src/command/add.dart
- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/global_activate.dart
- lib/src/command/lish.dart
- lib/src/command/remove.dart
- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
- lib/src/executable.dart
- lib/src/global_packages.dart
- lib/src/pub_embeddable_command.dart
- lib/src/solver/result.dart
- pubspec.yaml
Fixes: https://github.com/dart-lang/pub/issues/4074
> Remove support for sending analytics

- lib/src/sdk/flutter.dart
- test/add/sdk/sdk_test.dart
- test/deps_test.dart
- test/descriptor.dart
- test/embedding/ensure_pubspec_resolved.dart
- test/get/flutter_constraint_upper_bound_ignored_test.dart
- test/outdated/outdated_test.dart
- test/pinned_dependency_hint_test.dart
- test/sdk_test.dart
- test/solve_suggestions_test.dart
- test/validator/dependency_test.dart
- test/validator/flutter_constraint_test.dart
- test/version_solver_test.dart
https://github.com/dart-lang/pub/issues/4109
> Read flutter version from new location

- lib/src/source/git.dart
Fixes https://github.com/dart-lang/pub/issues/3404
> Use atomic moves when cloning git repos

- lib/src/entrypoint.dart
- lib/src/lock_file.dart
This is just a refactor - should make no difference.
The method needed a lot of info about the entrypoint, and therefore fits better there.
> Move packageConfigFile() to entrypoint.dart

- lib/src/sdk/flutter.dart
> Make FlutterSDK singleton, and move static members to non-static

- lib/src/git.dart
- lib/src/io.dart
- lib/src/validator/gitignore.dart
- test/validator/gitignore_test.dart
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a weekly cadence for reviewing PRs - please …
> fix: False detection of non-ignored files with non-ascii unicode characters

- lib/src/entrypoint.dart
This is a refactor only just moving code around and doing slight renamings.
Hopefully it will make upcoming diffs easier to read.
Next I want to make `ensureUptoDate` static, such that we can call it without creating an entrypoint.
> Move helpers inside ensureUpToDate

- lib/src/global_packages.dart
https://github.com/dart-lang/pub/issues/4185
> Fix calculation of padding in windows binstubs

- lib/src/sdk/flutter.dart
Follow up to https://github.com/dart-lang/pub/pull/4113
Fixes https://github.com/flutter/flutter/issues/145340
> update warning to fine in Flutter SDK version parsing

- lib/src/global_packages.dart
- test/global/binstubs/binstub_runs_global_run_if_no_snapshot_test.dart
- test/global/binstubs/explicit_executables_test.dart
- test/global/binstubs/path_package_test.dart
Follow up to https://github.com/dart-lang/pub/pull/4189
This should hopefully fix CI now.
> Use local pub in binstubs when testing

- test/embedding/embedding_test.dart
- test/test_pub.dart
- test/testdata/goldens/dependency_services/dependency_services_test/Adding transitive.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Compatible.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Finds smallest possible upgrade.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Ignoring version.txt
- test/testdata/goldens/dependency_services/dependency_services_test/No pubspec.lock.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Preserves no content-hashes.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Preserves pub.dartlang.org as hosted url.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Relative paths are allowed.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Removing transitive.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Smallest possible upgrade can upgrade beyond breaking.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Smallest possible upgrade can upgrade other packages if needed.txt
- test/testdata/goldens/dependency_services/dependency_services_test/multibreaking.txt
- test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt
https://github.com/dart-lang/pub/issues/4208
> Filter content hashes from golden files

- lib/src/pubspec.dart
- test/workspace_test.dart
> Error reporting for bad workspace paths

- lib/src/command.dart
- lib/src/command/add.dart
- lib/src/command/cache_add.dart
- lib/src/command/cache_clean.dart
- lib/src/command/deps.dart
- lib/src/command/downgrade.dart
- lib/src/command/get.dart
- lib/src/command/global_activate.dart
- lib/src/command/lish.dart
- lib/src/command/outdated.dart
- lib/src/command/remove.dart
- lib/src/command/token_add.dart
- lib/src/command/token_remove.dart
- lib/src/command/unpack.dart
- lib/src/command_runner.dart
- lib/src/executable.dart
- lib/src/utils.dart
- pubspec.yaml
- test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt
- tool/test-bin/pub_command_runner.dart
> Update package:args, more consistent helper usage

- test/embedding/embedding_test.dart
- test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt
Making the test slightly less brittle.
> Normalize whitespace in stacktrace golden

- lib/src/solver/solve_suggestions.dart
- test/workspace_test.dart
These don't work correctly, so disable for now.
See #4227
> Avoid trying to do suggestions for workspaces

- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
- lib/src/package.dart
- lib/src/pubspec.dart
- lib/src/source/git.dart
- lib/src/source/hosted.dart
- lib/src/system_cache.dart
- test/ascii_tree_test.dart
Attempts to make the code simpler. Should contain no functional changes.
> Refactor helpers for Package.load

- lib/src/command/downgrade.dart
- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
- test/downgrade/tighten_test.dart
- test/testdata/goldens/help_test/pub downgrade --help.txt
- test/testdata/goldens/upgrade/example_warns_about_major_versions_test/pub upgrade --major-versions does not update major versions in example~.txt
Fixes https://github.com/dart-lang/pub/issues/4241
> downgrade --tighten

- lib/src/command/deps.dart
- lib/src/command/upgrade.dart
- lib/src/entrypoint.dart
- lib/src/global_packages.dart
- lib/src/package.dart
- lib/src/solver/package_lister.dart
- lib/src/solver/report.dart
- lib/src/solver/result.dart
- lib/src/solver/version_solver.dart
- lib/src/validator/dependency_override.dart
- test/workspace_test.dart
https://github.com/dart-lang/pub/issues/4248
> Handle overrides in workspaces

- lib/src/package.dart
- test/workspace_test.dart
https://github.com/dart-lang/pub/issues/4237
> Validate that the same package cannot be overridden twice in workspace

- analysis_options.yaml
- test/ascii_tree_test.dart
- test/golden_file.dart
- test/validator/file_case_test.dart
- tool/test-bin/pub_command_runner.dart
Just recently learned about this cool lint!
Did not find too much though.
> Use lint unreachable_from_main

- lib/src/ascii_tree.dart
- lib/src/command/lish.dart
- lib/src/io.dart
- lib/src/package.dart
- test/lish/empy_directories_test.dart
- test/test_pub.dart
Fixes https://github.com/dart-lang/pub/issues/4262
> Include empty directories in published archives

- lib/src/command/dependency_services.dart
- test/testdata/goldens/dependency_services/dependency_services_test/No pubspec.lock.txt
- test/testdata/goldens/dependency_services/dependency_services_test/Removing transitive.txt
Small inconsistency.
I don't think we really use this constraint in dependabot anywhere consequential...
> Avoid quoting null constraint

- lib/src/command/dependency_services.dart
- lib/src/executable.dart
- lib/src/io.dart
- lib/src/package_graph.dart
- pubspec.yaml
* https://github.com/dart-lang/collection/pull/336
* https://github.com/dart-lang/collection/pull/332
> Fix deprecations from package:collection

- test/lish/archive_contents_test.dart
Seems this test is flaking sometimes.
> Fix ordering of listed files in test.

- lib/src/dart.dart
- pubspec.yaml
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
https://github.com/dart-lang/sdk/issues/56102
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
> Stop using deprecated ContextLocator and ContextBuilder.

- lib/src/source/hosted.dart
> Handle failure to retrieve status when testing advisory cache age

- lib/src/command/run.dart
Fixes https://github.com/dart-lang/pub/issues/4355
> call ensureUpToDate in `pub run`

- lib/src/validator.dart
- lib/src/validator/strict_dependencies.dart
- test/validator/strict_dependencies_test.dart
* https://github.com/dart-lang/native/issues/160
> Add `hook/` to strict dependencies check

- lib/src/package.dart
- pubspec.lock
- test/workspace_test.dart
> Better error for duplicate workspace entries

- lib/src/command/deps.dart
- test/deps_test.dart
- test/testdata/goldens/deps/executables_test/dev dependencies.txt
- test/workspace_test.dart
Discovered in https://github.com/flutter/flutter/issues/155727
> Fix `pub deps` behavior

- .github/dependabot.yml
After we added a pubspec.lock I think it makes sense to update it more often
> Do weekly dependabot checks

- lib/src/pubspec.dart
- pubspec.lock
- test/pubspec_test.dart
> Hint about sdk constraint update for workspace and resolution

- lib/src/entrypoint.dart
- test/workspace_test.dart
> Fix stray files check

- lib/src/entrypoint.dart
- lib/src/global_packages.dart
- test/package_graph_file_test.dart
- test/test_pub.dart
- test/testdata/goldens/embedding/embedding_test/logfile is written with --verbose and on unexpected exceptions.txt
> Write .dart_tool/package_graph.json when writing package_config.json

- lib/src/dart.dart
Context: https://dart-review.googlesource.com/c/sdk/+/426902
> Migrate `AnalysisError` to `Diagnostic`

- lib/src/command/deps.dart
Fixes https://github.com/dart-lang/pub/issues/4599
> Have `pub deps --json` quiet when no terminal is attached

- lib/src/io.dart
Should fix https://github.com/dart-lang/pub/issues/4598
> Retry renameFile operations on windows

- lib/src/source/hosted.dart
Should (hopefully) fix #4585 
git and global packages are "repaired" sequentially - so they should not cause a problem here.
> Restrict number of concurrently repaired hosted packages

- pubspec.lock
- test/check_resolution_up_to_date_test.dart
The delay was inserted at the wrong point.
> Attempt to decrease flakyness on windows CI 
